//! Static Imagine skill-id -> `(name, icon)` table, and the icon basenames
//! it references, compiled into the executable via `include_bytes!`.
//!
//! Generated by `scripts/gen-imagine-table.py` from the hand-curated
//! `crates/app/data/imagine_table.json`, itself derived from the game
//! client via BPSR-ZDPS; see `THIRD_PARTY_NOTICES.md`. Do not edit by hand.
//!
//! // IMAGINE-TAKEDOWN: not one of the five marked sites — this module is
//! // removed via `rm`, not edited in place. See `docs/plans/*imagines-plan.md`
//! // D4. Takedown removes this module, `crates/app/assets/imagines/`,
//! // `crates/app/data/imagine_table.json`, `scripts/prep-imagine-icons.py`,
//! // `scripts/gen-imagine-table.py`, and the five marked sites. Since the
//! // icons are compiled in (issue #123), an already-distributed copy needs
//! // a source deletion, rebuild, and re-release, not a directory deletion.
//!
//! Coverage is a hand-curated allowlist, not every skill id in the game —
//! an id outside the 106 curated Imagines yields `None` from
//! `imagine_of_skill_id`, and callers must treat that as "not an Imagine",
//! never as a lookup failure to surface.

/// One equippable Imagine's display data.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Imagine {
    pub name: &'static str,
    pub icon: &'static str,
}

/// Look up the Imagine a skill id belongs to, if `id` is one of the 106
/// curated ids. An id outside that set (including every excluded id in
/// `crates/app/data/imagine_table.json`'s `_excluded`) yields `None` —
/// that is the mechanism by which non-Imagine skill ids are dropped
/// rather than mis-rendered as a slot.
///
/// `name` is always the *canonical* (39xx) name for the id's icon, not
/// necessarily the id's own raw `SkillTable.json` name: identity is the
/// icon basename, not the name (spec's "Many-to-one is expected"). A
/// variant id whose own name disagrees with its canonical row (e.g.
/// `102651`'s raw name is "Boar Knight", but it shares an icon with
/// the canonical `3905` "Stunt! Boarrier Rush" and resolves to that
/// name here) must resolve to the canonical name — deduping by an id's
/// own raw name would let one equipped Imagine occupy both of a
/// player's two slots.
pub fn imagine_of_skill_id(id: i32) -> Option<Imagine> {
    Some(match id {
        3901 => Imagine {
            name: "Arcane! Flame Roar",
            icon: "skill_aoyi_skill_icon_017",
        },
        3902 => Imagine {
            name: "Arcane! Thunderfall Grasp",
            icon: "skill_aoyi_skill_icon_014",
        },
        3903 => Imagine {
            name: "Arcane! Blazing Axe",
            icon: "skill_aoyi_skill_icon_018",
        },
        3904 => Imagine {
            name: "Stunt! Super Critical",
            icon: "skill_aoyi_skill_icon_026",
        },
        3905 => Imagine {
            name: "Stunt! Boarrier Rush",
            icon: "skill_aoyi_skill_icon_001",
        },
        3906 => Imagine {
            name: "Arcane! Frostquake",
            icon: "skill_aoyi_skill_icon_015",
        },
        3907 => Imagine {
            name: "Stunt! Falling Star",
            icon: "skill_aoyi_skill_icon_008",
        },
        3908 => Imagine {
            name: "Arcane! Pulse Benediction",
            icon: "skill_aoyi_skill_icon_012",
        },
        3909 => Imagine {
            name: "Stunt! Fox Assault",
            icon: "skill_aoyi_skill_icon_011",
        },
        3910 => Imagine {
            name: "Stunt! Chaotic Barrage",
            icon: "skill_aoyi_skill_icon_009",
        },
        3911 => Imagine {
            name: "Arcane! Heart of Flame",
            icon: "skill_aoyi_skill_icon_042",
        },
        3913 => Imagine {
            name: "Stunt! Electro Bomb",
            icon: "skill_aoyi_skill_icon_010",
        },
        3914 => Imagine {
            name: "Stunt! Blade Sweep",
            icon: "skill_aoyi_skill_icon_019",
        },
        3915 => Imagine {
            name: "Stunt! Frenzied Shot",
            icon: "skill_aoyi_skill_icon_020",
        },
        3916 => Imagine {
            name: "Stunt! Piercing Arrow",
            icon: "skill_aoyi_skill_icon_021",
        },
        3917 => Imagine {
            name: "Stunt! Heavy Slash",
            icon: "skill_aoyi_skill_icon_022",
        },
        3918 => Imagine {
            name: "Arcane! Shadow of the Fox",
            icon: "skill_aoyi_skill_icon_023",
        },
        3919 => Imagine {
            name: "Arcane! Assault Turret",
            icon: "skill_aoyi_skill_icon_024",
        },
        3920 => Imagine {
            name: "Arcane! Blessing of Life",
            icon: "skill_aoyi_skill_icon_013",
        },
        3921 => Imagine {
            name: "Arcane! Time Decree",
            icon: "skill_aoyi_skill_icon_016",
        },
        3922 => Imagine {
            name: "Arcane! Flash Execution",
            icon: "skill_aoyi_skill_icon_025",
        },
        3923 => Imagine {
            name: "Arcane! Furious Hammer",
            icon: "skill_aoyi_skill_icon_005",
        },
        3924 => Imagine {
            name: "Stunt! Gale of Silence",
            icon: "skill_aoyi_skill_icon_027",
        },
        3925 => Imagine {
            name: "Stunt! Invisible Impact",
            icon: "skill_aoyi_skill_icon_028",
        },
        3926 => Imagine {
            name: "Arcane! Meteor Shower",
            icon: "skill_aoyi_skill_icon_029",
        },
        3927 => Imagine {
            name: "Stunt! Roar Command",
            icon: "skill_aoyi_skill_icon_030",
        },
        3928 => Imagine {
            name: "Stunt! Predator Slash",
            icon: "skill_aoyi_skill_icon_031",
        },
        3929 => Imagine {
            name: "Stunt! Shell Defense",
            icon: "skill_aoyi_skill_icon_032",
        },
        3930 => Imagine {
            name: "Stunt! Earth Shield",
            icon: "skill_aoyi_skill_icon_033",
        },
        3931 => Imagine {
            name: "Arcane! Shrine Field",
            icon: "skill_aoyi_skill_icon_034",
        },
        3932 => Imagine {
            name: "Stunt! Flamewheel Dance",
            icon: "skill_aoyi_skill_icon_035",
        },
        3933 => Imagine {
            name: "Stunt! Intimidating Roar",
            icon: "skill_aoyi_skill_icon_036",
        },
        3934 => Imagine {
            name: "Stunt! Blink Ambush",
            icon: "skill_aoyi_skill_icon_037",
        },
        3935 => Imagine {
            name: "Arcane! Thunder Roar",
            icon: "skill_aoyi_skill_icon_038",
        },
        3936 => Imagine {
            name: "Stunt! Water of Silence",
            icon: "skill_aoyi_skill_icon_039",
        },
        3937 => Imagine {
            name: "Stunt! Thunder Suppress",
            icon: "skill_aoyi_skill_icon_040",
        },
        3938 => Imagine {
            name: "Arcane! Cocoon Tech",
            icon: "skill_aoyi_skill_icon_041",
        },
        3939 => Imagine {
            name: "Stunt! Lightning Orb",
            icon: "skill_aoyi_skill_icon_043",
        },
        3940 => Imagine {
            name: "Stunt! Whirlwind Strike",
            icon: "skill_aoyi_skill_icon_044",
        },
        3941 => Imagine {
            name: "Stunt! Transform into Bee",
            icon: "skill_aoyi_skill_icon_045",
        },
        3942 => Imagine {
            name: "Arcane! Poison Explosion",
            icon: "skill_aoyi_skill_icon_046",
        },
        3943 => Imagine {
            name: "Arcane! Infernal Thrust",
            icon: "skill_aoyi_skill_icon_047",
        },
        3944 => Imagine {
            name: "Arcane! Azure Gale",
            icon: "skill_aoyi_skill_icon_048",
        },
        3945 => Imagine {
            name: "Arcane! Silent Tide",
            icon: "skill_aoyi_skill_icon_049",
        },
        3946 => Imagine {
            name: "Arcane! Goblin March",
            icon: "skill_aoyi_skill_icon_050",
        },
        3947 => Imagine {
            name: "Stunt! Spiral Severance",
            icon: "skill_aoyi_skill_icon_051",
        },
        3948 => Imagine {
            name: "Arcane! Divine Reliance",
            icon: "skill_aoyi_skill_icon_052",
        },
        3949 => Imagine {
            name: "Arcane! Illusion Resonance",
            icon: "skill_aoyi_skill_icon_053",
        },
        3950 => Imagine {
            name: "Arcane! Allscape Sublimation",
            icon: "skill_aoyi_skill_icon_055",
        },
        3951 => Imagine {
            name: "Arcane! Guardian's Boundary",
            icon: "skill_aoyi_skill_icon_054",
        },
        3952 => Imagine {
            name: "Arcane! Blazing Flames",
            icon: "skill_aoyi_skill_icon_058",
        },
        3953 => Imagine {
            name: "Arcane! Peerless Thrust",
            icon: "skill_aoyi_skill_icon_063",
        },
        3954 => Imagine {
            name: "Arcane! Phantom Ambush",
            icon: "skill_aoyi_skill_icon_068",
        },
        3955 => Imagine {
            name: "Arcane! Cabbage Hammer",
            icon: "skill_aoyi_skill_icon_066",
        },
        3956 => Imagine {
            name: "Arcane! Flame Spirit's Fortune",
            icon: "skill_aoyi_skill_icon_070",
        },
        3957 => Imagine {
            name: "Arcane! Fatal Spiral",
            icon: "skill_aoyi_skill_icon_057",
        },
        3958 => Imagine {
            name: "Stunt! Frost Breath",
            icon: "skill_aoyi_skill_icon_056",
        },
        3959 => Imagine {
            name: "Stunt! Lightning Smite",
            icon: "skill_aoyi_skill_icon_060",
        },
        3960 => Imagine {
            name: "Stunt! Blade Storm",
            icon: "skill_aoyi_skill_icon_059",
        },
        3961 => Imagine {
            name: "Stunt! Carpet Bombing",
            icon: "skill_aoyi_skill_icon_061",
        },
        3962 => Imagine {
            name: "Stunt! Healing Bomb",
            icon: "skill_aoyi_skill_icon_062",
        },
        3963 => Imagine {
            name: "Stunt! Kinetic Strike",
            icon: "skill_aoyi_skill_icon_067",
        },
        3964 => Imagine {
            name: "Stunt! Cabbage Boomerang",
            icon: "skill_aoyi_skill_icon_064",
        },
        3965 => Imagine {
            name: "Stunt! Cabbage Blitz",
            icon: "skill_aoyi_skill_icon_065",
        },
        3966 => Imagine {
            name: "Stunt! Twin Fangs",
            icon: "skill_aoyi_skill_icon_069",
        },
        3968 => Imagine {
            name: "Arcane! Void Corruption Blade",
            icon: "skill_aoyi_skill_icon_071",
        },
        3969 => Imagine {
            name: "Arcane! Rift Recoil",
            icon: "skill_aoyi_skill_icon_072",
        },
        3970 => Imagine {
            name: "Arcane! Command Quadrant",
            icon: "skill_aoyi_skill_icon_073",
        },
        3971 => Imagine {
            name: "Arcane! Superconductor Surge",
            icon: "skill_aoyi_skill_icon_074",
        },
        3972 => Imagine {
            name: "Arcane! Shuttle Fang",
            icon: "skill_aoyi_skill_icon_075",
        },
        3973 => Imagine {
            name: "Arcane! Flash Stomp",
            icon: "skill_aoyi_skill_icon_076",
        },
        3974 => Imagine {
            name: "Arcane! Precision Burst",
            icon: "skill_aoyi_skill_icon_077",
        },
        3975 => Imagine {
            name: "Arcane! Piercing Roar",
            icon: "skill_aoyi_skill_icon_078",
        },
        3976 => Imagine {
            name: "Arcane! Swift Devour",
            icon: "skill_aoyi_skill_icon_079",
        },
        3977 => Imagine {
            name: "Stunt! Hidden Strike",
            icon: "skill_aoyi_skill_icon_080",
        },
        3978 => Imagine {
            name: "Stunt! Absolute Zero",
            icon: "skill_aoyi_skill_icon_081",
        },
        3979 => Imagine {
            name: "Stunt! Abyssal Breath",
            icon: "skill_aoyi_skill_icon_082",
        },
        3980 => Imagine {
            name: "Stunt! Ground Smash",
            icon: "skill_aoyi_skill_icon_083",
        },
        3981 => Imagine {
            name: "Stunt! Lock-On Shot",
            icon: "skill_aoyi_skill_icon_084",
        },
        3982 => Imagine {
            name: "Arcane! Celestial Spirit Mage",
            icon: "skill_aoyi_skill_icon_086",
        },
        3983 => Imagine {
            name: "Arcane! Dragon Slayer",
            icon: "skill_aoyi_skill_icon_085",
        },
        3986 => Imagine {
            name: "Arcane! Celestial Spirit Mage",
            icon: "skill_aoyi_skill_icon_086",
        },
        3987 => Imagine {
            name: "Arcane! Dragon Slayer",
            icon: "skill_aoyi_skill_icon_085",
        },
        102640 => Imagine {
            name: "Stunt! Boarrier Rush",
            icon: "skill_aoyi_skill_icon_001",
        },
        102651 => Imagine {
            name: "Stunt! Boarrier Rush",
            icon: "skill_aoyi_skill_icon_001",
        },
        102655 => Imagine {
            name: "Stunt! Boarrier Rush",
            icon: "skill_aoyi_skill_icon_001",
        },
        102658 => Imagine {
            name: "Stunt! Boarrier Rush",
            icon: "skill_aoyi_skill_icon_001",
        },
        420140 => Imagine {
            name: "Stunt! Chaotic Barrage",
            icon: "skill_aoyi_skill_icon_009",
        },
        1002440 => Imagine {
            name: "Stunt! Super Critical",
            icon: "skill_aoyi_skill_icon_026",
        },
        1002830 => Imagine {
            name: "Arcane! Frostquake",
            icon: "skill_aoyi_skill_icon_015",
        },
        1005240 => Imagine {
            name: "Stunt! Predator Slash",
            icon: "skill_aoyi_skill_icon_031",
        },
        1006940 => Imagine {
            name: "Arcane! Cocoon Tech",
            icon: "skill_aoyi_skill_icon_041",
        },
        1008640 => Imagine {
            name: "Stunt! Falling Star",
            icon: "skill_aoyi_skill_icon_008",
        },
        1008641 => Imagine {
            name: "Stunt! Whirlwind Strike",
            icon: "skill_aoyi_skill_icon_044",
        },
        1010440 => Imagine {
            name: "Stunt! Thunder Suppress",
            icon: "skill_aoyi_skill_icon_040",
        },
        1010540 => Imagine {
            name: "Stunt! Water of Silence",
            icon: "skill_aoyi_skill_icon_039",
        },
        1700440 => Imagine {
            name: "Arcane! Furious Hammer",
            icon: "skill_aoyi_skill_icon_005",
        },
        2001740 => Imagine {
            name: "Stunt! Blink Ambush",
            icon: "skill_aoyi_skill_icon_037",
        },
        2002440 => Imagine {
            name: "Arcane! Thunderfall Grasp",
            icon: "skill_aoyi_skill_icon_014",
        },
        2002441 => Imagine {
            name: "Arcane! Thunderfall Grasp",
            icon: "skill_aoyi_skill_icon_014",
        },
        2002840 => Imagine {
            name: "Arcane! Meteor Shower",
            icon: "skill_aoyi_skill_icon_029",
        },
        2900240 => Imagine {
            name: "Arcane! Blessing of Life",
            icon: "skill_aoyi_skill_icon_013",
        },
        2900241 => Imagine {
            name: "Arcane! Blessing of Life",
            icon: "skill_aoyi_skill_icon_013",
        },
        2900340 => Imagine {
            name: "Arcane! Time Decree",
            icon: "skill_aoyi_skill_icon_016",
        },
        2900540 => Imagine {
            name: "Arcane! Flash Execution",
            icon: "skill_aoyi_skill_icon_025",
        },
        2900640 => Imagine {
            name: "Arcane! Heart of Flame",
            icon: "skill_aoyi_skill_icon_042",
        },
        _ => return None,
    })
}

/// Generates `IMAGINE_ICON_FILES` (every icon basename referenced by
/// `imagine_of_skill_id`) and `IMAGINE_ICON_BYTES` (each of those
/// basenames paired with its PNG, compiled in via `include_bytes!`)
/// from one literal list, so the two cannot silently disagree. Mirrors
/// `class_icons!` in `icons.rs`, but without an exhaustive match — the
/// key set is an open-ended game-data id, not a small fixed enum, so
/// there is no "missing variant" compile-time guarantee to buy.
/// `IMAGINE_ICON_FILES` is `#[cfg(test)]`-gated: production code only
/// needs `IMAGINE_ICON_BYTES` (which pairs each basename with its
/// bytes), so the basename-only list would otherwise be dead code in a
/// release build. `icons.rs`'s tests reference it across the module
/// boundary, which is fine — `cfg(test)` applies crate-wide under
/// `cargo test`, so both sides see it.
macro_rules! imagine_icons {
    ($($name:literal),+ $(,)?) => {
        #[cfg(test)]
        pub const IMAGINE_ICON_FILES: &[&str] = &[$($name),+];
        pub const IMAGINE_ICON_BYTES: &[(&str, &[u8])] = &[
            $(( $name, include_bytes!(concat!("../assets/imagines/", $name, ".png")) )),+
        ];
    };
}
imagine_icons! {
    "skill_aoyi_skill_icon_001",
    "skill_aoyi_skill_icon_005",
    "skill_aoyi_skill_icon_008",
    "skill_aoyi_skill_icon_009",
    "skill_aoyi_skill_icon_010",
    "skill_aoyi_skill_icon_011",
    "skill_aoyi_skill_icon_012",
    "skill_aoyi_skill_icon_013",
    "skill_aoyi_skill_icon_014",
    "skill_aoyi_skill_icon_015",
    "skill_aoyi_skill_icon_016",
    "skill_aoyi_skill_icon_017",
    "skill_aoyi_skill_icon_018",
    "skill_aoyi_skill_icon_019",
    "skill_aoyi_skill_icon_020",
    "skill_aoyi_skill_icon_021",
    "skill_aoyi_skill_icon_022",
    "skill_aoyi_skill_icon_023",
    "skill_aoyi_skill_icon_024",
    "skill_aoyi_skill_icon_025",
    "skill_aoyi_skill_icon_026",
    "skill_aoyi_skill_icon_027",
    "skill_aoyi_skill_icon_028",
    "skill_aoyi_skill_icon_029",
    "skill_aoyi_skill_icon_030",
    "skill_aoyi_skill_icon_031",
    "skill_aoyi_skill_icon_032",
    "skill_aoyi_skill_icon_033",
    "skill_aoyi_skill_icon_034",
    "skill_aoyi_skill_icon_035",
    "skill_aoyi_skill_icon_036",
    "skill_aoyi_skill_icon_037",
    "skill_aoyi_skill_icon_038",
    "skill_aoyi_skill_icon_039",
    "skill_aoyi_skill_icon_040",
    "skill_aoyi_skill_icon_041",
    "skill_aoyi_skill_icon_042",
    "skill_aoyi_skill_icon_043",
    "skill_aoyi_skill_icon_044",
    "skill_aoyi_skill_icon_045",
    "skill_aoyi_skill_icon_046",
    "skill_aoyi_skill_icon_047",
    "skill_aoyi_skill_icon_048",
    "skill_aoyi_skill_icon_049",
    "skill_aoyi_skill_icon_050",
    "skill_aoyi_skill_icon_051",
    "skill_aoyi_skill_icon_052",
    "skill_aoyi_skill_icon_053",
    "skill_aoyi_skill_icon_054",
    "skill_aoyi_skill_icon_055",
    "skill_aoyi_skill_icon_056",
    "skill_aoyi_skill_icon_057",
    "skill_aoyi_skill_icon_058",
    "skill_aoyi_skill_icon_059",
    "skill_aoyi_skill_icon_060",
    "skill_aoyi_skill_icon_061",
    "skill_aoyi_skill_icon_062",
    "skill_aoyi_skill_icon_063",
    "skill_aoyi_skill_icon_064",
    "skill_aoyi_skill_icon_065",
    "skill_aoyi_skill_icon_066",
    "skill_aoyi_skill_icon_067",
    "skill_aoyi_skill_icon_068",
    "skill_aoyi_skill_icon_069",
    "skill_aoyi_skill_icon_070",
    "skill_aoyi_skill_icon_071",
    "skill_aoyi_skill_icon_072",
    "skill_aoyi_skill_icon_073",
    "skill_aoyi_skill_icon_074",
    "skill_aoyi_skill_icon_075",
    "skill_aoyi_skill_icon_076",
    "skill_aoyi_skill_icon_077",
    "skill_aoyi_skill_icon_078",
    "skill_aoyi_skill_icon_079",
    "skill_aoyi_skill_icon_080",
    "skill_aoyi_skill_icon_081",
    "skill_aoyi_skill_icon_082",
    "skill_aoyi_skill_icon_083",
    "skill_aoyi_skill_icon_084",
    "skill_aoyi_skill_icon_085",
    "skill_aoyi_skill_icon_086",
}

#[cfg(test)]
/// `(id, name, icon)` for every curated Imagine — the emitted tests iterate
/// this to exercise the `match` from outside, since a `match` itself can't
/// be iterated.
const ALL_ENTRIES: &[(i32, &str, &str)] = &[
    (3901, "Arcane! Flame Roar", "skill_aoyi_skill_icon_017"),
    (
        3902,
        "Arcane! Thunderfall Grasp",
        "skill_aoyi_skill_icon_014",
    ),
    (3903, "Arcane! Blazing Axe", "skill_aoyi_skill_icon_018"),
    (3904, "Stunt! Super Critical", "skill_aoyi_skill_icon_026"),
    (3905, "Stunt! Boarrier Rush", "skill_aoyi_skill_icon_001"),
    (3906, "Arcane! Frostquake", "skill_aoyi_skill_icon_015"),
    (3907, "Stunt! Falling Star", "skill_aoyi_skill_icon_008"),
    (
        3908,
        "Arcane! Pulse Benediction",
        "skill_aoyi_skill_icon_012",
    ),
    (3909, "Stunt! Fox Assault", "skill_aoyi_skill_icon_011"),
    (3910, "Stunt! Chaotic Barrage", "skill_aoyi_skill_icon_009"),
    (3911, "Arcane! Heart of Flame", "skill_aoyi_skill_icon_042"),
    (3913, "Stunt! Electro Bomb", "skill_aoyi_skill_icon_010"),
    (3914, "Stunt! Blade Sweep", "skill_aoyi_skill_icon_019"),
    (3915, "Stunt! Frenzied Shot", "skill_aoyi_skill_icon_020"),
    (3916, "Stunt! Piercing Arrow", "skill_aoyi_skill_icon_021"),
    (3917, "Stunt! Heavy Slash", "skill_aoyi_skill_icon_022"),
    (
        3918,
        "Arcane! Shadow of the Fox",
        "skill_aoyi_skill_icon_023",
    ),
    (3919, "Arcane! Assault Turret", "skill_aoyi_skill_icon_024"),
    (
        3920,
        "Arcane! Blessing of Life",
        "skill_aoyi_skill_icon_013",
    ),
    (3921, "Arcane! Time Decree", "skill_aoyi_skill_icon_016"),
    (3922, "Arcane! Flash Execution", "skill_aoyi_skill_icon_025"),
    (3923, "Arcane! Furious Hammer", "skill_aoyi_skill_icon_005"),
    (3924, "Stunt! Gale of Silence", "skill_aoyi_skill_icon_027"),
    (3925, "Stunt! Invisible Impact", "skill_aoyi_skill_icon_028"),
    (3926, "Arcane! Meteor Shower", "skill_aoyi_skill_icon_029"),
    (3927, "Stunt! Roar Command", "skill_aoyi_skill_icon_030"),
    (3928, "Stunt! Predator Slash", "skill_aoyi_skill_icon_031"),
    (3929, "Stunt! Shell Defense", "skill_aoyi_skill_icon_032"),
    (3930, "Stunt! Earth Shield", "skill_aoyi_skill_icon_033"),
    (3931, "Arcane! Shrine Field", "skill_aoyi_skill_icon_034"),
    (3932, "Stunt! Flamewheel Dance", "skill_aoyi_skill_icon_035"),
    (
        3933,
        "Stunt! Intimidating Roar",
        "skill_aoyi_skill_icon_036",
    ),
    (3934, "Stunt! Blink Ambush", "skill_aoyi_skill_icon_037"),
    (3935, "Arcane! Thunder Roar", "skill_aoyi_skill_icon_038"),
    (3936, "Stunt! Water of Silence", "skill_aoyi_skill_icon_039"),
    (3937, "Stunt! Thunder Suppress", "skill_aoyi_skill_icon_040"),
    (3938, "Arcane! Cocoon Tech", "skill_aoyi_skill_icon_041"),
    (3939, "Stunt! Lightning Orb", "skill_aoyi_skill_icon_043"),
    (3940, "Stunt! Whirlwind Strike", "skill_aoyi_skill_icon_044"),
    (
        3941,
        "Stunt! Transform into Bee",
        "skill_aoyi_skill_icon_045",
    ),
    (
        3942,
        "Arcane! Poison Explosion",
        "skill_aoyi_skill_icon_046",
    ),
    (3943, "Arcane! Infernal Thrust", "skill_aoyi_skill_icon_047"),
    (3944, "Arcane! Azure Gale", "skill_aoyi_skill_icon_048"),
    (3945, "Arcane! Silent Tide", "skill_aoyi_skill_icon_049"),
    (3946, "Arcane! Goblin March", "skill_aoyi_skill_icon_050"),
    (3947, "Stunt! Spiral Severance", "skill_aoyi_skill_icon_051"),
    (3948, "Arcane! Divine Reliance", "skill_aoyi_skill_icon_052"),
    (
        3949,
        "Arcane! Illusion Resonance",
        "skill_aoyi_skill_icon_053",
    ),
    (
        3950,
        "Arcane! Allscape Sublimation",
        "skill_aoyi_skill_icon_055",
    ),
    (
        3951,
        "Arcane! Guardian's Boundary",
        "skill_aoyi_skill_icon_054",
    ),
    (3952, "Arcane! Blazing Flames", "skill_aoyi_skill_icon_058"),
    (3953, "Arcane! Peerless Thrust", "skill_aoyi_skill_icon_063"),
    (3954, "Arcane! Phantom Ambush", "skill_aoyi_skill_icon_068"),
    (3955, "Arcane! Cabbage Hammer", "skill_aoyi_skill_icon_066"),
    (
        3956,
        "Arcane! Flame Spirit's Fortune",
        "skill_aoyi_skill_icon_070",
    ),
    (3957, "Arcane! Fatal Spiral", "skill_aoyi_skill_icon_057"),
    (3958, "Stunt! Frost Breath", "skill_aoyi_skill_icon_056"),
    (3959, "Stunt! Lightning Smite", "skill_aoyi_skill_icon_060"),
    (3960, "Stunt! Blade Storm", "skill_aoyi_skill_icon_059"),
    (3961, "Stunt! Carpet Bombing", "skill_aoyi_skill_icon_061"),
    (3962, "Stunt! Healing Bomb", "skill_aoyi_skill_icon_062"),
    (3963, "Stunt! Kinetic Strike", "skill_aoyi_skill_icon_067"),
    (
        3964,
        "Stunt! Cabbage Boomerang",
        "skill_aoyi_skill_icon_064",
    ),
    (3965, "Stunt! Cabbage Blitz", "skill_aoyi_skill_icon_065"),
    (3966, "Stunt! Twin Fangs", "skill_aoyi_skill_icon_069"),
    (
        3968,
        "Arcane! Void Corruption Blade",
        "skill_aoyi_skill_icon_071",
    ),
    (3969, "Arcane! Rift Recoil", "skill_aoyi_skill_icon_072"),
    (
        3970,
        "Arcane! Command Quadrant",
        "skill_aoyi_skill_icon_073",
    ),
    (
        3971,
        "Arcane! Superconductor Surge",
        "skill_aoyi_skill_icon_074",
    ),
    (3972, "Arcane! Shuttle Fang", "skill_aoyi_skill_icon_075"),
    (3973, "Arcane! Flash Stomp", "skill_aoyi_skill_icon_076"),
    (3974, "Arcane! Precision Burst", "skill_aoyi_skill_icon_077"),
    (3975, "Arcane! Piercing Roar", "skill_aoyi_skill_icon_078"),
    (3976, "Arcane! Swift Devour", "skill_aoyi_skill_icon_079"),
    (3977, "Stunt! Hidden Strike", "skill_aoyi_skill_icon_080"),
    (3978, "Stunt! Absolute Zero", "skill_aoyi_skill_icon_081"),
    (3979, "Stunt! Abyssal Breath", "skill_aoyi_skill_icon_082"),
    (3980, "Stunt! Ground Smash", "skill_aoyi_skill_icon_083"),
    (3981, "Stunt! Lock-On Shot", "skill_aoyi_skill_icon_084"),
    (
        3982,
        "Arcane! Celestial Spirit Mage",
        "skill_aoyi_skill_icon_086",
    ),
    (3983, "Arcane! Dragon Slayer", "skill_aoyi_skill_icon_085"),
    (
        3986,
        "Arcane! Celestial Spirit Mage",
        "skill_aoyi_skill_icon_086",
    ),
    (3987, "Arcane! Dragon Slayer", "skill_aoyi_skill_icon_085"),
    (102640, "Stunt! Boarrier Rush", "skill_aoyi_skill_icon_001"),
    (102651, "Boar Knight", "skill_aoyi_skill_icon_001"),
    (102655, "Boar Impact!", "skill_aoyi_skill_icon_001"),
    (102658, "Stunt! Boarrier Rush", "skill_aoyi_skill_icon_001"),
    (
        420140,
        "Stunt! Chaotic Barrage",
        "skill_aoyi_skill_icon_009",
    ),
    (
        1002440,
        "Stunt! Super Critical",
        "skill_aoyi_skill_icon_026",
    ),
    (1002830, "Arcane! Frostquake", "skill_aoyi_skill_icon_015"),
    (
        1005240,
        "Stunt! Predator Slash",
        "skill_aoyi_skill_icon_031",
    ),
    (1006940, "Arcane! Cocoon Tech", "skill_aoyi_skill_icon_041"),
    (1008640, "Stunt! Falling Star", "skill_aoyi_skill_icon_008"),
    (
        1008641,
        "Stunt! Whirlwind Strike",
        "skill_aoyi_skill_icon_044",
    ),
    (
        1010440,
        "Stunt! Thunder Suppress",
        "skill_aoyi_skill_icon_040",
    ),
    (
        1010540,
        "Stunt! Water of Silence",
        "skill_aoyi_skill_icon_039",
    ),
    (
        1700440,
        "Arcane! Furious Hammer",
        "skill_aoyi_skill_icon_005",
    ),
    (2001740, "Stunt! Blink Ambush", "skill_aoyi_skill_icon_037"),
    (
        2002440,
        "Arcane! Thunderfall Grasp",
        "skill_aoyi_skill_icon_014",
    ),
    (
        2002441,
        "Arcane! Thunderfall Grasp",
        "skill_aoyi_skill_icon_014",
    ),
    (2002840, "Arcane! Swift Vortex", "skill_aoyi_skill_icon_029"),
    (
        2900240,
        "Arcane! Blessing of Life",
        "skill_aoyi_skill_icon_013",
    ),
    (
        2900241,
        "Arcane! Blessing of Life",
        "skill_aoyi_skill_icon_013",
    ),
    (2900340, "Arcane! Time Decree", "skill_aoyi_skill_icon_016"),
    (
        2900540,
        "Arcane! Flash Execution",
        "skill_aoyi_skill_icon_025",
    ),
    (
        2900640,
        "Arcane! Heart of Flame",
        "skill_aoyi_skill_icon_042",
    ),
];

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn entry_count_is_106() {
        assert_eq!(ALL_ENTRIES.len(), 106);
    }

    #[test]
    fn distinct_name_and_icon_counts() {
        let names: HashSet<&str> = ALL_ENTRIES.iter().map(|(_, name, _)| *name).collect();
        let icons: HashSet<&str> = ALL_ENTRIES.iter().map(|(_, _, icon)| *icon).collect();
        assert_eq!(names.len(), 84);
        assert_eq!(icons.len(), 81);
    }

    #[test]
    fn every_all_entries_icon_is_in_icon_files() {
        let files: HashSet<&str> = IMAGINE_ICON_FILES.iter().copied().collect();
        for (_, _, icon) in ALL_ENTRIES {
            assert!(
                files.contains(icon),
                "icon {icon} referenced by ALL_ENTRIES but missing from IMAGINE_ICON_FILES"
            );
        }
    }

    #[test]
    fn icon_files_len_is_81() {
        assert_eq!(IMAGINE_ICON_FILES.len(), 81);
    }

    #[test]
    fn many_to_one_group_resolves_to_the_same_imagine() {
        // Spec's "Many-to-one is expected — identity is the icon basename":
        // these five ids are tier/class variants of the same Boar Imagine.
        // `102651` and `102655` have their own, divergent raw names in
        // SkillTable.json ("Boar Knight", "Boar Impact!"), but
        // `imagine_of_skill_id` must resolve every one of them to the
        // *canonical* (39xx) name and icon — otherwise a Boar player
        // equipping a variant id would read as two different Imagines and
        // occupy both of their two slots.
        let canonical = imagine_of_skill_id(3905).unwrap();
        assert_eq!(canonical.name, "Stunt! Boarrier Rush");
        for id in [3905, 102640, 102651, 102655, 102658] {
            assert_eq!(imagine_of_skill_id(id).unwrap(), canonical);
        }
    }

    #[test]
    fn another_variant_resolves_to_its_canonical_name() {
        // `2002840`'s own raw name is "Arcane! Swift Vortex"; its icon's
        // canonical (39xx) name is "Arcane! Meteor Shower".
        assert_eq!(
            imagine_of_skill_id(2_002_840).unwrap().name,
            "Arcane! Meteor Shower"
        );
    }

    #[test]
    fn spot_check_a_known_entry() {
        let imagine = imagine_of_skill_id(3905).unwrap();
        assert_eq!(imagine.name, "Stunt! Boarrier Rush");
        assert_eq!(imagine.icon, "skill_aoyi_skill_icon_001");
    }

    #[test]
    fn excluded_and_unknown_ids_are_none() {
        // Every spec-excluded id (docs/specs/2026-08-17-issue-33-imagines-spec.md
        // "Curation") plus an arbitrary id that was never in SkillTable.json.
        for id in [
            3000,
            3601,
            706103,
            4310,
            102659,
            2350,
            2351,
            2900270,
            2900370,
            2900570,
            999_999_999,
        ] {
            assert_eq!(imagine_of_skill_id(id), None);
        }
    }
}
