#!/usr/bin/env python3
"""Regenerate `crates/app/src/skill_icons.rs` from the committed skill icons.

`crates/app/assets/skills/` holds the vendored, downscaled, circle-masked skill
icons (issue #192) prepared by `scripts/prep-skill-icons.py`. This script turns
that directory listing into the `skill_icons!` macro invocation that
`include_bytes!`s each one into the executable, so the compiled-in set and the
committed set cannot drift apart — the same generate-don't-hand-maintain
rationale as `scripts/gen-imagine-table.py` -> `crates/app/src/imagines.rs`.

The directory listing, not the vendored id -> icon table
(`crates/meter/data/SkillOverridesIcons.json`), is the input on purpose. That
table names every icon BPSR-ZDPS references, including basenames whose art is
not present upstream and therefore not shipped here; compiling in only what is
actually committed keeps `include_bytes!` from naming a missing file, and the
runtime lookup already degrades a basename with no texture to a blank
placeholder.

Usage:

    python3 scripts/gen-skill-icons.py          # regenerate from the committed PNGs
    python3 scripts/gen-skill-icons.py --check  # offline: fail if skill_icons.rs is stale

Run `cargo fmt -p ShinraMeter-BPSR` after a regeneration.
`.github/workflows/name-tables.yml` runs `--check` so the generated file cannot
rot silently.
"""

import argparse
import io
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ASSETS = ROOT / "crates" / "app" / "assets" / "skills"
OUT = ROOT / "crates" / "app" / "src" / "skill_icons.rs"

# What a basename is allowed to be. These names end up inside a `concat!` path
# in an `include_bytes!`, so anything with a quote, a backslash or a path
# separator in it must be rejected here rather than emitted into Rust source.
# `scripts/gen-name-tables.py`'s `_ICON_BASENAME_RE` enforces the same shape on
# the table side.
BASENAME_RE = re.compile(r"^[A-Za-z0-9_.-]+$")

HEADER = '''//! The vendored skill-row icon basenames, compiled into the executable via
//! `include_bytes!` (issue #192).
//!
//! Generated by `scripts/gen-skill-icons.py` from the PNGs committed under
//! `crates/app/assets/skills/`, themselves prepared by
//! `scripts/prep-skill-icons.py` from the game client via BPSR-ZDPS; see
//! `THIRD_PARTY_NOTICES.md`. Do not edit by hand.
//!
//! This module is only the *bytes* half of skill icons. The skill id -> icon
//! basename half is `bpsr_meter::tables::skill_icon`, generated separately by
//! `scripts/gen-name-tables.py`. The two are deliberately not required to
//! agree: that table names every icon BPSR-ZDPS references, this module
//! carries only the subset whose art is actually committed here, and
//! `crate::icons::SkillIcons::get` returns `None` for the difference so the
//! row paints a blank placeholder instead of panicking.

/// Generates `SKILL_ICON_FILES` (every committed icon basename) and
/// `SKILL_ICON_BYTES` (each of those basenames paired with its PNG, compiled
/// in via `include_bytes!`) from one literal list, so the two cannot silently
/// disagree. Mirrors `imagine_icons!` in `crate::imagines`, for the same
/// reason and with the same `#[cfg(test)]` gate on the basename-only list:
/// production code only ever needs the pairs.
macro_rules! skill_icons {
    ($($name:literal),+ $(,)?) => {
        #[cfg(test)]
        pub const SKILL_ICON_FILES: &[&str] = &[$($name),+];
        pub const SKILL_ICON_BYTES: &[(&str, &[u8])] = &[
            $(( $name, include_bytes!(concat!("../assets/skills/", $name, ".png")) )),+
        ];
    };
}
skill_icons! {
'''

FOOTER = "}\n"


def render(names: list[str]) -> str:
    out = io.StringIO()
    out.write(HEADER)
    for name in names:
        out.write(f'    "{name}",\n')
    out.write(FOOTER)
    return out.getvalue()


def _self_test() -> None:
    """Fast synthetic checks run on every invocation. Same rationale as
    `scripts/gen-name-tables.py`'s `_self_test`: there is no Python test
    harness in this repo, so this hard-fails inline.
    """
    assert BASENAME_RE.match("weapon_mz-01_kx06")
    assert not BASENAME_RE.match("From Shield Combo talent")
    assert not BASENAME_RE.match("../evil")
    assert not BASENAME_RE.match('quote"')
    rendered = render(["a", "b"])
    assert rendered.endswith('    "a",\n    "b",\n}\n'), rendered[-40:]


def main() -> None:
    _self_test()

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; fail if the generated file is stale",
    )
    args = parser.parse_args()

    names = sorted(p.stem for p in ASSETS.glob("*.png"))
    if not names:
        sys.exit(f"no icons committed under {ASSETS}")
    bad = [n for n in names if not BASENAME_RE.match(n)]
    if bad:
        sys.exit(f"{len(bad)} icon name(s) unfit for an include_bytes! path: {', '.join(bad)}")

    rendered = render(names)
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else None
    if current == rendered:
        print(f"skill_icons.rs is up to date ({len(names)} icons)")
        return
    if args.check:
        sys.exit(
            f"skill_icons.rs is stale: regenerate with "
            f"`python3 scripts/gen-skill-icons.py` and run `cargo fmt`"
        )
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT} ({len(names)} icons)")


if __name__ == "__main__":
    main()
