#!/usr/bin/env python3
"""Regenerate `crates/meter/src/tables.rs` from the vendored name tables.

The community trackers publish their monster and scene name maps as JSON. We
keep verbatim copies under `crates/meter/data/` for provenance and compile them
into `match` arms so the lookup is free at runtime and the binary carries no
JSON parser for them.

To refresh, re-download the sources into `crates/meter/data/` and run this:

    curl -sLo crates/meter/data/MonsterName.json \\
      https://raw.githubusercontent.com/resonance-logs/resonance-logs/main/src-tauri/meter-data/MonsterName.json
    curl -sLo crates/meter/data/SceneName.json \\
      https://raw.githubusercontent.com/resonance-logs/resonance-logs/main/src-tauri/meter-data/SceneName.json
    curl -sLo crates/meter/data/MonsterNameCrowdsource.json \\
      https://raw.githubusercontent.com/winjwinj/bpsr-logs/main/src/lib/data/json/MonsterNameCrowdsource.json
    python3 scripts/gen-name-tables.py && cargo fmt -p bpsr-meter
"""

import io
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "crates" / "meter" / "data"
OUT = ROOT / "crates" / "meter" / "src" / "tables.rs"

HEADER = """//! Static id -> display-name tables for monsters and scenes.
//!
//! Generated by `scripts/gen-name-tables.py` from the community-maintained
//! tables under `crates/meter/data/`, shipped by the `resonance-logs` and
//! `bpsr-logs` trackers (both GPL-3.0, the same licence as this project); see
//! `THIRD_PARTY_NOTICES.md`. Do not edit by hand.
//!
//! Coverage is partial - these tables name the monsters and instances the
//! community has catalogued, not every entity in the game. An unknown id yields
//! `None`, and callers fall back to showing the raw id.
"""

FOOTER = """
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names_a_known_raid_boss() {
        assert_eq!(monster_name(1013), Some("Rathalos"));
    }

    #[test]
    fn crowdsourced_names_win_over_the_bulk_table() {
        assert_eq!(monster_name(10086), Some("Goblin King"));
    }

    #[test]
    fn names_a_known_scene() {
        assert_eq!(scene_name(1001), Some("Tina's Mindrealm"));
    }

    #[test]
    fn unknown_ids_are_none() {
        assert_eq!(monster_name(0), None);
        assert_eq!(scene_name(0), None);
    }
}
"""


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit(out: io.StringIO, doc: str, fn: str, table: dict) -> None:
    out.write(f"\n{doc}\npub fn {fn}(id: u32) -> Option<&'static str> {{\n")
    out.write("    Some(match id {\n")
    for key in sorted(table):
        out.write('        %d => "%s",\n' % (key, esc(table[key])))
    out.write("        _ => return None,\n    })\n}\n")


def main() -> None:
    bulk = json.loads((DATA / "MonsterName.json").read_text())
    curated = json.loads((DATA / "MonsterNameCrowdsource.json").read_text())
    scenes = json.loads((DATA / "SceneName.json").read_text())

    monsters = {int(k): v for k, v in bulk.items()}
    # The crowdsourced list is hand-checked, so it wins where the two disagree.
    monsters.update({int(k): v for k, v in curated.items()})

    out = io.StringIO()
    out.write(HEADER)
    emit(
        out,
        "/// Display name for a monster template id, if the community table names it.",
        "monster_name",
        monsters,
    )
    emit(
        out,
        "/// Display name for a scene (map/instance) id, if the community table names it.",
        "scene_name",
        {int(k): v for k, v in scenes.items()},
    )
    out.write(FOOTER)
    OUT.write_text(out.getvalue())
    print(f"wrote {OUT}: {len(monsters)} monsters, {len(scenes)} scenes")


if __name__ == "__main__":
    main()
