#!/usr/bin/env python3
"""Regenerate `crates/app/src/imagines.rs` from the vendored Imagine table.

`crates/app/data/imagine_table.json` is a hand-curated, game-client-derived
table (via BPSR-ZDPS) of the 106 skill ids that are actually equippable
Imagines — see `docs/specs/2026-08-17-issue-33-imagines-spec.md`'s
"Curation" section for how the 125 slot-7/8 `SkillTable.json` rows were
narrowed to 106 by hand-excluding talent-passive stubs, non-player
abilities, and stand-in cosmetics. We keep a verbatim copy for provenance
and compile it into a `match` arm so the lookup is free at runtime and the
binary carries no JSON parser for it — same rationale as
`scripts/gen-name-tables.py` -> `crates/meter/src/tables.rs`.

The icon PNGs referenced by the table are prepared separately by
`scripts/prep-imagine-icons.py` into `crates/app/assets/imagines/`; this
script does not touch them, but it refuses to emit unless every icon
basename the table references resolves to a committed PNG there.

Usage:

    python3 scripts/gen-imagine-table.py          # regenerate from the vendored JSON
    python3 scripts/gen-imagine-table.py --check  # offline: fail if imagines.rs is stale

Refresh only after re-curating `crates/app/data/imagine_table.json`, and run
`cargo fmt -p ShinraMeter-BPSR` after a regeneration. There is no `--refresh`
counterpart to `scripts/gen-name-tables.py`'s: this generator has no networked
upstream: its inputs are the committed curated JSON and the committed PNGs.
`.github/workflows/name-tables.yml` runs `--check` so the generated file cannot
rot silently.
"""

import argparse
import io
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "crates" / "app" / "data" / "imagine_table.json"
ASSETS = ROOT / "crates" / "app" / "assets" / "imagines"
OUT = ROOT / "crates" / "app" / "src" / "imagines.rs"

HEADER = """//! Static Imagine skill-id -> `(name, icon)` table, and the icon basenames
//! it references, loaded from `assets/imagines/` beside the exe at runtime.
//!
//! Generated by `scripts/gen-imagine-table.py` from the hand-curated
//! `crates/app/data/imagine_table.json`, itself derived from the game
//! client via BPSR-ZDPS; see `THIRD_PARTY_NOTICES.md`. Do not edit by hand.
//!
//! // IMAGINE-TAKEDOWN: not one of the five marked sites — this module is
//! // removed via `rm`, not edited in place. See `docs/plans/*imagines-plan.md`
//! // D4. Takedown removes this module, `crates/app/assets/imagines/`,
//! // `crates/app/data/imagine_table.json`, `scripts/prep-imagine-icons.py`,
//! // `scripts/gen-imagine-table.py`, and the five marked sites — now a
//! // directory deletion (`rm -r crates/app/assets/imagines/`) for an
//! // already-distributed copy, not a rebuild.
//!
//! Coverage is a hand-curated allowlist, not every skill id in the game —
//! an id outside the 106 curated Imagines yields `None` from
//! `imagine_of_skill_id`, and callers must treat that as "not an Imagine",
//! never as a lookup failure to surface.
"""


def esc(s: str) -> str:
    """Escape `s` for embedding in a Rust `&'static str` literal.

    Order matters: backslash is escaped first, so the escapes this function
    inserts below are never themselves re-escaped. `\\r`, `\\n`, and `\\t`
    get Rust's short forms; every other control character gets Rust's
    `\\u{...}` form, so a bare CR (or any other control byte) in a future
    re-curation of the vendored JSON can never produce an `imagines.rs` that
    fails to compile with "bare CR not allowed in string" or similar.
    """
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    out = []
    for ch in s:
        if ch == "\r":
            out.append("\\r")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append(f"\\u{{{ord(ch):x}}}")
        else:
            out.append(ch)
    return "".join(out)


def _self_test() -> None:
    """Fast synthetic checks run on every generation. There is no Python
    test harness elsewhere in this repo (no pytest config, no CI job that
    runs Python — see `scripts/` and `.github/workflows/`), so this
    hard-fails inline instead of living in an untested, never-run test
    file.
    """
    assert esc('a\\b"c') == 'a\\\\b\\"c'
    assert esc("line1\rline2") == "line1\\rline2"
    assert esc("line1\nline2") == "line1\\nline2"
    assert esc("a\tb") == "a\\tb"
    assert esc("\x01") == "\\u{1}"
    assert esc("\x7f") == "\\u{7f}"
    # Order: backslash-escaping must not re-escape a literal `\r` that was
    # already produced for a real carriage return.
    assert esc("\\\r") == "\\\\\\r"

    # rustfmt-shape replication: the inline/broken-out decision is made on the
    # joined element list, and the broken-out form carries a trailing comma.
    # Getting either wrong makes `--check` permanently red against a
    # `cargo fmt`-clean file, which is the failure mode this pair exists to
    # avoid.
    assert _fits(["a", "bb"], 5)  # "a, bb" is exactly the budget
    assert not _fits(["a", "bb"], 4)
    assert _fits([], 0)
    assert _broken_out("    ", ["x", "y"]) == "        x,\n        y,\n"
    assert _broken_out("", []) == ""

    # canonical_name_by_icon: happy path — the 39xx canonical rows win,
    # non-canonical rows (e.g. a 102xxx variant sharing the same icon) are
    # ignored when building the map.
    canon = canonical_name_by_icon(
        [
            {"id": 3901, "name": "A", "icon": "icon_a"},
            {"id": 3902, "name": "B", "icon": "icon_b"},
            {"id": 102640, "name": "not the canonical name", "icon": "icon_a"},
        ]
    )
    assert canon == {"icon_a": "A", "icon_b": "B"}

    # canonical_name_by_icon: two canonical (39xx) rows disagreeing on the
    # name for the same icon breaks the bijection this whole scheme relies
    # on and must hard-fail rather than silently pick one.
    try:
        canonical_name_by_icon(
            [
                {"id": 3901, "name": "A", "icon": "icon_a"},
                {"id": 3902, "name": "A-prime", "icon": "icon_a"},
            ]
        )
        raise AssertionError("expected SystemExit for a non-bijective canonical range")
    except SystemExit:
        pass

    # resolve_canonical_names: a variant resolves to the canonical name, not
    # its own (possibly divergent) raw name.
    resolved = resolve_canonical_names(
        [
            {"id": 3901, "name": "A", "icon": "icon_a"},
            {"id": 102640, "name": "variant's own wrong name", "icon": "icon_a"},
        ],
        {"icon_a": "A"},
    )
    assert resolved == {3901: "A", 102640: "A"}

    # resolve_canonical_names: an "orphan" icon with no canonical entry must
    # hard-fail rather than fall back to the variant's own name — that
    # fallback is exactly the bug this resolution step exists to fix.
    try:
        resolve_canonical_names([{"id": 999, "name": "Orphan", "icon": "icon_zzz"}], {})
        raise AssertionError("expected SystemExit for an orphan icon")
    except SystemExit:
        pass


def canonical_name_by_icon(entries: list[dict]) -> dict[str, str]:
    """Icon basename -> canonical display name, built only from ids in the
    3900-3999 "canonical" range (spec's "Many-to-one is expected — identity
    is the icon basename"). A canonical icon must name exactly one Imagine —
    if two canonical rows disagree, "the canonical name" is not well-defined
    and the curated data is broken, so this hard-fails rather than picking a
    winner.
    """
    canonical: dict[str, str] = {}
    for e in entries:
        if 3900 <= e["id"] < 4000:
            icon, name = e["icon"], e["name"]
            if icon in canonical and canonical[icon] != name:
                raise SystemExit(
                    f"refusing to emit: canonical icon {icon!r} names both "
                    f"{canonical[icon]!r} and {name!r} among ids 3900-3999 - "
                    "the icon<->name bijection in the canonical range is broken"
                )
            canonical[icon] = name
    return canonical


def resolve_canonical_names(entries: list[dict], canonical: dict[str, str]) -> dict[int, str]:
    """id -> canonical display name for every entry, resolving a variant id
    to its canonical (39xx) name via icon identity — the fix for the bug
    caught in review: deduping by an id's own raw name let one equipped
    Imagine occupy both of a player's slots (e.g. `3905` and `102651` both
    render "the Boar Imagine" but had different raw names). Every entry's
    icon must already be in `canonical` (the spec's "zero orphans" claim);
    an orphan hard-fails instead of silently falling back to the variant's
    own name, which would reintroduce that bug.
    """
    resolved: dict[int, str] = {}
    orphans: list[int] = []
    for e in entries:
        name = canonical.get(e["icon"])
        if name is None:
            orphans.append(e["id"])
        else:
            resolved[e["id"]] = name
    if orphans:
        raise SystemExit(
            "refusing to emit: these ids reference an icon with no canonical "
            f"(3900-3999) name - orphan icons: {sorted(orphans)}"
        )
    return resolved


# rustfmt's own wrapping rules, replicated here so `render()` emits byte-for-byte
# what `cargo fmt` would produce. Without this the generated file and the
# committed file could only ever agree after a `cargo fmt` pass, and `--check`
# would need a Rust toolchain it deliberately does not have — the same reason
# `scripts/gen-name-tables.py` reproduces rustfmt's array packing in
# `_BOSS_IDS_LINE_WIDTH`. Both numbers are rustfmt defaults (`fn_call_width` is
# the budget a tuple literal's element list gets before rustfmt breaks it one
# element per line; `struct_lit_width` is the same budget for a struct
# literal's fields), and this repo ships no `rustfmt.toml` overriding them.
_FN_CALL_WIDTH = 60
_STRUCT_LIT_WIDTH = 18


def _fits(items: list[str], budget: int) -> bool:
    """Whether rustfmt would keep `items` inline inside their delimiters."""
    return len(", ".join(items)) <= budget


def _broken_out(indent: str, items: list[str]) -> str:
    """rustfmt's broken-out form: one element per line, each trailing-comma'd."""
    return "".join(f"{indent}    {item},\n" for item in items)


def emit_lookup(out: io.StringIO, entries: list[dict], canonical_name_of_id: dict[int, str]) -> None:
    out.write(
        "\n/// One equippable Imagine's display data.\n"
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n"
        "pub struct Imagine {\n"
        "    pub name: &'static str,\n"
        "    pub icon: &'static str,\n"
        "}\n"
    )
    out.write(
        "\n/// Look up the Imagine a skill id belongs to, if `id` is one of the 106\n"
        "/// curated ids. An id outside that set (including every excluded id in\n"
        "/// `crates/app/data/imagine_table.json`'s `_excluded`) yields `None` —\n"
        "/// that is the mechanism by which non-Imagine skill ids are dropped\n"
        "/// rather than mis-rendered as a slot.\n"
        "///\n"
        "/// `name` is always the *canonical* (39xx) name for the id's icon, not\n"
        "/// necessarily the id's own raw `SkillTable.json` name: identity is the\n"
        "/// icon basename, not the name (spec's \"Many-to-one is expected\"). A\n"
        "/// variant id whose own name disagrees with its canonical row (e.g.\n"
        "/// `102651`'s raw name is \"Boar Knight\", but it shares an icon with\n"
        "/// the canonical `3905` \"Stunt! Boarrier Rush\" and resolves to that\n"
        "/// name here) must resolve to the canonical name — deduping by an id's\n"
        "/// own raw name would let one equipped Imagine occupy both of a\n"
        "/// player's two slots.\n"
        "pub fn imagine_of_skill_id(id: i32) -> Option<Imagine> {\n"
        "    Some(match id {\n"
    )
    for e in sorted(entries, key=lambda e: e["id"]):
        fields = [
            'name: "%s"' % esc(canonical_name_of_id[e["id"]]),
            'icon: "%s"' % esc(e["icon"]),
        ]
        head = "        %d => Imagine" % e["id"]
        if _fits(fields, _STRUCT_LIT_WIDTH):
            out.write("%s { %s },\n" % (head, ", ".join(fields)))
        else:
            out.write("%s {\n%s        },\n" % (head, _broken_out("        ", fields)))
    out.write("        _ => return None,\n    })\n}\n")


def emit_icon_files(out: io.StringIO, icons: list[str]) -> None:
    out.write(
        "\n/// Every icon basename referenced by `imagine_of_skill_id`. These are\n"
        "/// not embedded: the app reads `<assets>/imagines/<basename>.png` off\n"
        "/// disk at runtime (see `crate::assets` and `icons.rs`'s `ImagineIcons`).\n"
        "/// Non-exhaustive `&[&str]` form (mirrors `TOOLBAR_ICON_BYTES` in\n"
        "/// `icons.rs`), not an exhaustive macro like `class_icons!` — the key\n"
        "/// set is an open-ended game-data id, not a small fixed enum, so there\n"
        "/// is no \"missing variant\" compile-time guarantee to buy.\n"
        "pub const IMAGINE_ICON_FILES: &[&str] = &[\n"
    )
    for icon in sorted(icons):
        out.write('    "%s",\n' % esc(icon))
    out.write("];\n")


FOOTER_HEADER = """
#[cfg(test)]
/// `(id, name, icon)` for every curated Imagine — the emitted tests iterate
/// this to exercise the `match` from outside, since a `match` itself can't
/// be iterated.
const ALL_ENTRIES: &[(i32, &str, &str)] = &[
"""

FOOTER_TAIL = """
#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn entry_count_is_106() {
        assert_eq!(ALL_ENTRIES.len(), 106);
    }

    #[test]
    fn distinct_name_and_icon_counts() {
        let names: HashSet<&str> = ALL_ENTRIES.iter().map(|(_, name, _)| *name).collect();
        let icons: HashSet<&str> = ALL_ENTRIES.iter().map(|(_, _, icon)| *icon).collect();
        assert_eq!(names.len(), 84);
        assert_eq!(icons.len(), 81);
    }

    #[test]
    fn every_all_entries_icon_is_in_icon_files() {
        let files: HashSet<&str> = IMAGINE_ICON_FILES.iter().copied().collect();
        for (_, _, icon) in ALL_ENTRIES {
            assert!(
                files.contains(icon),
                "icon {icon} referenced by ALL_ENTRIES but missing from IMAGINE_ICON_FILES"
            );
        }
    }

    #[test]
    fn icon_files_len_is_81() {
        assert_eq!(IMAGINE_ICON_FILES.len(), 81);
    }

    #[test]
    fn many_to_one_group_resolves_to_the_same_imagine() {
        // Spec's "Many-to-one is expected — identity is the icon basename":
        // these five ids are tier/class variants of the same Boar Imagine.
        // `102651` and `102655` have their own, divergent raw names in
        // SkillTable.json ("Boar Knight", "Boar Impact!"), but
        // `imagine_of_skill_id` must resolve every one of them to the
        // *canonical* (39xx) name and icon — otherwise a Boar player
        // equipping a variant id would read as two different Imagines and
        // occupy both of their two slots.
        let canonical = imagine_of_skill_id(3905).unwrap();
        assert_eq!(canonical.name, "Stunt! Boarrier Rush");
        for id in [3905, 102640, 102651, 102655, 102658] {
            assert_eq!(imagine_of_skill_id(id).unwrap(), canonical);
        }
    }

    #[test]
    fn another_variant_resolves_to_its_canonical_name() {
        // `2002840`'s own raw name is "Arcane! Swift Vortex"; its icon's
        // canonical (39xx) name is "Arcane! Meteor Shower".
        assert_eq!(
            imagine_of_skill_id(2_002_840).unwrap().name,
            "Arcane! Meteor Shower"
        );
    }

    #[test]
    fn spot_check_a_known_entry() {
        let imagine = imagine_of_skill_id(3905).unwrap();
        assert_eq!(imagine.name, "Stunt! Boarrier Rush");
        assert_eq!(imagine.icon, "skill_aoyi_skill_icon_001");
    }

    #[test]
    fn excluded_and_unknown_ids_are_none() {
        // Every spec-excluded id (docs/specs/2026-08-17-issue-33-imagines-spec.md
        // "Curation") plus an arbitrary id that was never in SkillTable.json.
        for id in [
            3000,
            3601,
            706103,
            4310,
            102659,
            2350,
            2351,
            2900270,
            2900370,
            2900570,
            999_999_999,
        ] {
            assert_eq!(imagine_of_skill_id(id), None);
        }
    }
}
"""


def emit_all_entries(out: io.StringIO, entries: list[dict]) -> None:
    out.write(FOOTER_HEADER)
    for e in sorted(entries, key=lambda e: e["id"]):
        items = ["%d" % e["id"], '"%s"' % esc(e["name"]), '"%s"' % esc(e["icon"])]
        if _fits(items, _FN_CALL_WIDTH):
            out.write("    (%s),\n" % ", ".join(items))
        else:
            out.write("    (\n%s    ),\n" % _broken_out("    ", items))
    out.write("];\n")
    out.write(FOOTER_TAIL)


def render() -> str:
    """Build the full text of `imagines.rs` from the vendored JSON and assets.

    Every pre-emit invariant lives here rather than on the write path, so
    `--check` enforces exactly the same refusals a regeneration would.
    """
    table = json.loads(DATA.read_text(encoding="utf-8"))
    entries = table["imagines"]
    counts = table["_counts"]

    assert len(entries) == counts["imagines"], (
        f"imagine_table.json: {len(entries)} entries in 'imagines' but "
        f"_counts.imagines says {counts['imagines']}"
    )
    distinct_names = {e["name"] for e in entries}
    distinct_icons = {e["icon"] for e in entries}
    assert len(distinct_names) == counts["distinct_names"], (
        f"imagine_table.json: {len(distinct_names)} distinct names but "
        f"_counts.distinct_names says {counts['distinct_names']}"
    )
    assert len(distinct_icons) == counts["distinct_icons"], (
        f"imagine_table.json: {len(distinct_icons)} distinct icons but "
        f"_counts.distinct_icons says {counts['distinct_icons']}"
    )

    missing = sorted(
        icon for icon in distinct_icons if not (ASSETS / f"{icon}.png").is_file()
    )
    if missing:
        raise SystemExit(
            "refusing to emit: the following icon basenames are referenced by "
            f"imagine_table.json but have no PNG under {ASSETS}:\n  "
            + "\n  ".join(missing)
        )

    # Identity-is-the-icon invariants (design correction after review caught
    # the original name-dedup bug): these are what make "resolve every id to
    # its canonical (39xx) name" a safe, well-defined operation. Data-
    # dependent, so — like the asset-existence check above — they run here
    # rather than in `_self_test()`, which only exercises the pure helpers
    # against synthetic data.
    canonical_range = [e for e in entries if 3900 <= e["id"] < 4000]
    canonical_range_icons = {e["icon"] for e in canonical_range}
    canonical_range_names = {e["name"] for e in canonical_range}
    if len(canonical_range_icons) != 81 or len(canonical_range_names) != 81:
        raise SystemExit(
            "refusing to emit: expected exactly 81 distinct icons and 81 "
            "distinct names among ids 3900-3999 (the canonical range), got "
            f"{len(canonical_range_icons)} icons / {len(canonical_range_names)} names"
        )
    canonical_by_icon = canonical_name_by_icon(entries)  # raises if non-bijective
    if len(set(canonical_by_icon.values())) != len(canonical_by_icon):
        raise SystemExit(
            "refusing to emit: two different canonical icons share the same "
            "canonical name - the icon<->name bijection is broken"
        )
    canonical_name_of_id = resolve_canonical_names(entries, canonical_by_icon)  # raises on orphans
    assert set(canonical_name_of_id) == {e["id"] for e in entries}, (
        "canonical-name resolution must be total over every curated id"
    )

    out = io.StringIO()
    out.write(HEADER)
    emit_lookup(out, entries, canonical_name_of_id)
    emit_icon_files(out, sorted(distinct_icons))
    emit_all_entries(out, entries)
    print(
        f"{len(entries)} imagines, {len(distinct_names)} distinct raw names, "
        f"{len(distinct_icons)} distinct icons, {len(canonical_by_icon)} canonical names",
        file=sys.stderr,
    )
    return out.getvalue()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit 1 if the generated file is out of date",
    )
    args = parser.parse_args()

    _self_test()

    rendered = render()
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else None
        if current != rendered:
            was = "missing" if current is None else f"{len(current)} chars"
            print(f"DRIFT: {OUT} is out of date ({was} on disk, {len(rendered)} chars generated)")
            print("\nrun `python3 scripts/gen-imagine-table.py` and commit the result")
            sys.exit(1)
        print("imagine table is up to date")
        return

    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
