#!/usr/bin/env python3
"""Regenerate `crates/app/src/imagines.rs` from the vendored Imagine table.

`crates/app/data/imagine_table.json` is a hand-curated, game-client-derived
table (via BPSR-ZDPS) of the 106 skill ids that are actually equippable
Imagines — see `docs/specs/2026-08-17-issue-33-imagines-spec.md`'s
"Curation" section for how the 125 slot-7/8 `SkillTable.json` rows were
narrowed to 106 by hand-excluding talent-passive stubs, non-player
abilities, and stand-in cosmetics. We keep a verbatim copy for provenance
and compile it into a `match` arm so the lookup is free at runtime and the
binary carries no JSON parser for it — same rationale as
`scripts/gen-name-tables.py` -> `crates/meter/src/tables.rs`.

The icon PNGs referenced by the table are prepared separately by
`scripts/prep-imagine-icons.py` into `crates/app/assets/imagines/`; this
script does not touch them, but it refuses to emit unless every icon
basename the table references resolves to a committed PNG there.

To refresh (only after re-curating `crates/app/data/imagine_table.json`):

    python3 scripts/gen-imagine-table.py && cargo fmt -p ShinraMeter-BPSR
"""

import io
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "crates" / "app" / "data" / "imagine_table.json"
ASSETS = ROOT / "crates" / "app" / "assets" / "imagines"
OUT = ROOT / "crates" / "app" / "src" / "imagines.rs"

HEADER = """//! Static Imagine skill-id -> `(name, icon)` table, and the embedded icon
//! PNGs it references.
//!
//! Generated by `scripts/gen-imagine-table.py` from the hand-curated
//! `crates/app/data/imagine_table.json`, itself derived from the game
//! client via BPSR-ZDPS; see `THIRD_PARTY_NOTICES.md`. Do not edit by hand.
//!
//! // IMAGINE-TAKEDOWN: one of five sites — see `docs/plans/*imagines-plan.md`
//! // D4. Takedown removes this module, `crates/app/assets/imagines/`,
//! // `crates/app/data/imagine_table.json`, `scripts/prep-imagine-icons.py`,
//! // `scripts/gen-imagine-table.py`, and the other four marked sites.
//!
//! Coverage is a hand-curated allowlist, not every skill id in the game —
//! an id outside the 106 curated Imagines yields `None` from
//! `imagine_of_skill_id`, and callers must treat that as "not an Imagine",
//! never as a lookup failure to surface.
"""


def esc(s: str) -> str:
    """Escape `s` for embedding in a Rust `&'static str` literal.

    Order matters: backslash is escaped first, so the escapes this function
    inserts below are never themselves re-escaped. `\\r`, `\\n`, and `\\t`
    get Rust's short forms; every other control character gets Rust's
    `\\u{...}` form, so a bare CR (or any other control byte) in a future
    re-curation of the vendored JSON can never produce an `imagines.rs` that
    fails to compile with "bare CR not allowed in string" or similar.
    """
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    out = []
    for ch in s:
        if ch == "\r":
            out.append("\\r")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append(f"\\u{{{ord(ch):x}}}")
        else:
            out.append(ch)
    return "".join(out)


def _self_test() -> None:
    """Fast synthetic checks run on every generation. There is no Python
    test harness elsewhere in this repo (no pytest config, no CI job that
    runs Python — see `scripts/` and `.github/workflows/`), so this
    hard-fails inline instead of living in an untested, never-run test
    file.
    """
    assert esc('a\\b"c') == 'a\\\\b\\"c'
    assert esc("line1\rline2") == "line1\\rline2"
    assert esc("line1\nline2") == "line1\\nline2"
    assert esc("a\tb") == "a\\tb"
    assert esc("\x01") == "\\u{1}"
    assert esc("\x7f") == "\\u{7f}"
    # Order: backslash-escaping must not re-escape a literal `\r` that was
    # already produced for a real carriage return.
    assert esc("\\\r") == "\\\\\\r"

    # canonical_name_by_icon: happy path — the 39xx canonical rows win,
    # non-canonical rows (e.g. a 102xxx variant sharing the same icon) are
    # ignored when building the map.
    canon = canonical_name_by_icon(
        [
            {"id": 3901, "name": "A", "icon": "icon_a"},
            {"id": 3902, "name": "B", "icon": "icon_b"},
            {"id": 102640, "name": "not the canonical name", "icon": "icon_a"},
        ]
    )
    assert canon == {"icon_a": "A", "icon_b": "B"}

    # canonical_name_by_icon: two canonical (39xx) rows disagreeing on the
    # name for the same icon breaks the bijection this whole scheme relies
    # on and must hard-fail rather than silently pick one.
    try:
        canonical_name_by_icon(
            [
                {"id": 3901, "name": "A", "icon": "icon_a"},
                {"id": 3902, "name": "A-prime", "icon": "icon_a"},
            ]
        )
        raise AssertionError("expected SystemExit for a non-bijective canonical range")
    except SystemExit:
        pass

    # resolve_canonical_names: a variant resolves to the canonical name, not
    # its own (possibly divergent) raw name.
    resolved = resolve_canonical_names(
        [
            {"id": 3901, "name": "A", "icon": "icon_a"},
            {"id": 102640, "name": "variant's own wrong name", "icon": "icon_a"},
        ],
        {"icon_a": "A"},
    )
    assert resolved == {3901: "A", 102640: "A"}

    # resolve_canonical_names: an "orphan" icon with no canonical entry must
    # hard-fail rather than fall back to the variant's own name — that
    # fallback is exactly the bug this resolution step exists to fix.
    try:
        resolve_canonical_names([{"id": 999, "name": "Orphan", "icon": "icon_zzz"}], {})
        raise AssertionError("expected SystemExit for an orphan icon")
    except SystemExit:
        pass


def canonical_name_by_icon(entries: list[dict]) -> dict[str, str]:
    """Icon basename -> canonical display name, built only from ids in the
    3900-3999 "canonical" range (spec's "Many-to-one is expected — identity
    is the icon basename"). A canonical icon must name exactly one Imagine —
    if two canonical rows disagree, "the canonical name" is not well-defined
    and the curated data is broken, so this hard-fails rather than picking a
    winner.
    """
    canonical: dict[str, str] = {}
    for e in entries:
        if 3900 <= e["id"] < 4000:
            icon, name = e["icon"], e["name"]
            if icon in canonical and canonical[icon] != name:
                raise SystemExit(
                    f"refusing to emit: canonical icon {icon!r} names both "
                    f"{canonical[icon]!r} and {name!r} among ids 3900-3999 - "
                    "the icon<->name bijection in the canonical range is broken"
                )
            canonical[icon] = name
    return canonical


def resolve_canonical_names(entries: list[dict], canonical: dict[str, str]) -> dict[int, str]:
    """id -> canonical display name for every entry, resolving a variant id
    to its canonical (39xx) name via icon identity — the fix for the bug
    caught in review: deduping by an id's own raw name let one equipped
    Imagine occupy both of a player's slots (e.g. `3905` and `102651` both
    render "the Boar Imagine" but had different raw names). Every entry's
    icon must already be in `canonical` (the spec's "zero orphans" claim);
    an orphan hard-fails instead of silently falling back to the variant's
    own name, which would reintroduce that bug.
    """
    resolved: dict[int, str] = {}
    orphans: list[int] = []
    for e in entries:
        name = canonical.get(e["icon"])
        if name is None:
            orphans.append(e["id"])
        else:
            resolved[e["id"]] = name
    if orphans:
        raise SystemExit(
            "refusing to emit: these ids reference an icon with no canonical "
            f"(3900-3999) name - orphan icons: {sorted(orphans)}"
        )
    return resolved


def emit_lookup(out: io.StringIO, entries: list[dict], canonical_name_of_id: dict[int, str]) -> None:
    out.write(
        "\n/// One equippable Imagine's display data.\n"
        "#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n"
        "pub struct Imagine {\n"
        "    pub name: &'static str,\n"
        "    pub icon: &'static str,\n"
        "}\n"
    )
    out.write(
        "\n/// Look up the Imagine a skill id belongs to, if `id` is one of the 106\n"
        "/// curated ids. An id outside that set (including every excluded id in\n"
        "/// `crates/app/data/imagine_table.json`'s `_excluded`) yields `None` —\n"
        "/// that is the mechanism by which non-Imagine skill ids are dropped\n"
        "/// rather than mis-rendered as a slot.\n"
        "///\n"
        "/// `name` is always the *canonical* (39xx) name for the id's icon, not\n"
        "/// necessarily the id's own raw `SkillTable.json` name: identity is the\n"
        "/// icon basename, not the name (spec's \"Many-to-one is expected\"). A\n"
        "/// variant id whose own name disagrees with its canonical row (e.g.\n"
        "/// `102651`'s raw name is \"Boar Knight\", but it shares an icon with\n"
        "/// the canonical `3905` \"Stunt! Boarrier Rush\" and resolves to that\n"
        "/// name here) must resolve to the canonical name — deduping by an id's\n"
        "/// own raw name would let one equipped Imagine occupy both of a\n"
        "/// player's two slots.\n"
        "pub fn imagine_of_skill_id(id: i32) -> Option<Imagine> {\n"
        "    Some(match id {\n"
    )
    for e in sorted(entries, key=lambda e: e["id"]):
        out.write(
            '        %d => Imagine { name: "%s", icon: "%s" },\n'
            % (e["id"], esc(canonical_name_of_id[e["id"]]), esc(e["icon"]))
        )
    out.write("        _ => return None,\n    })\n}\n")


def emit_icon_bytes(out: io.StringIO, icons: list[str]) -> None:
    out.write(
        "\n/// Every icon basename referenced by `imagine_of_skill_id`, paired with\n"
        "/// its embedded PNG. Non-exhaustive `&[(key, bytes)]` form (mirrors\n"
        "/// `TOOLBAR_ICON_BYTES` in `icons.rs`), not an exhaustive macro like\n"
        "/// `class_icons!` — the key set is an open-ended game-data id, not a\n"
        "/// small fixed enum, so there is no \"missing variant\" compile-time\n"
        "/// guarantee to buy.\n"
        "pub const IMAGINE_ICON_BYTES: &[(&str, &[u8])] = &[\n"
    )
    for icon in sorted(icons):
        out.write(
            '    ("%s", include_bytes!("../assets/imagines/%s.png")),\n'
            % (esc(icon), icon)
        )
    out.write("];\n")


FOOTER_HEADER = """
#[cfg(test)]
/// `(id, name, icon)` for every curated Imagine — the emitted tests iterate
/// this to exercise the `match` from outside, since a `match` itself can't
/// be iterated.
const ALL_ENTRIES: &[(i32, &str, &str)] = &[
"""

FOOTER_TAIL = """
#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn entry_count_is_106() {
        assert_eq!(ALL_ENTRIES.len(), 106);
    }

    #[test]
    fn distinct_name_and_icon_counts() {
        let names: HashSet<&str> = ALL_ENTRIES.iter().map(|(_, name, _)| *name).collect();
        let icons: HashSet<&str> = ALL_ENTRIES.iter().map(|(_, _, icon)| *icon).collect();
        assert_eq!(names.len(), 84);
        assert_eq!(icons.len(), 81);
    }

    #[test]
    fn every_all_entries_icon_is_in_icon_bytes() {
        let embedded: HashSet<&str> = IMAGINE_ICON_BYTES.iter().map(|(k, _)| *k).collect();
        for (_, _, icon) in ALL_ENTRIES {
            assert!(
                embedded.contains(icon),
                "icon {icon} referenced by ALL_ENTRIES but missing from IMAGINE_ICON_BYTES"
            );
        }
    }

    #[test]
    fn icon_bytes_len_is_81() {
        assert_eq!(IMAGINE_ICON_BYTES.len(), 81);
    }

    #[test]
    fn many_to_one_group_resolves_to_the_same_imagine() {
        // Spec's "Many-to-one is expected — identity is the icon basename":
        // these five ids are tier/class variants of the same Boar Imagine.
        // `102651` and `102655` have their own, divergent raw names in
        // SkillTable.json ("Boar Knight", "Boar Impact!"), but
        // `imagine_of_skill_id` must resolve every one of them to the
        // *canonical* (39xx) name and icon — otherwise a Boar player
        // equipping a variant id would read as two different Imagines and
        // occupy both of their two slots.
        let canonical = imagine_of_skill_id(3905).unwrap();
        assert_eq!(canonical.name, "Stunt! Boarrier Rush");
        for id in [3905, 102640, 102651, 102655, 102658] {
            assert_eq!(imagine_of_skill_id(id).unwrap(), canonical);
        }
    }

    #[test]
    fn another_variant_resolves_to_its_canonical_name() {
        // `2002840`'s own raw name is "Arcane! Swift Vortex"; its icon's
        // canonical (39xx) name is "Arcane! Meteor Shower".
        assert_eq!(
            imagine_of_skill_id(2_002_840).unwrap().name,
            "Arcane! Meteor Shower"
        );
    }

    #[test]
    fn spot_check_a_known_entry() {
        let imagine = imagine_of_skill_id(3905).unwrap();
        assert_eq!(imagine.name, "Stunt! Boarrier Rush");
        assert_eq!(imagine.icon, "skill_aoyi_skill_icon_001");
    }

    #[test]
    fn excluded_and_unknown_ids_are_none() {
        // Every spec-excluded id (docs/specs/2026-08-17-issue-33-imagines-spec.md
        // "Curation") plus an arbitrary id that was never in SkillTable.json.
        for id in [
            3000, 3601, 706103, 4310, 102659, 2350, 2351, 2900270, 2900370, 2900570,
            999_999_999,
        ] {
            assert_eq!(imagine_of_skill_id(id), None);
        }
    }
}
"""


def emit_all_entries(out: io.StringIO, entries: list[dict]) -> None:
    out.write(FOOTER_HEADER)
    for e in sorted(entries, key=lambda e: e["id"]):
        out.write('    (%d, "%s", "%s"),\n' % (e["id"], esc(e["name"]), esc(e["icon"])))
    out.write("];\n")
    out.write(FOOTER_TAIL)


def main() -> None:
    _self_test()

    table = json.loads(DATA.read_text())
    entries = table["imagines"]
    counts = table["_counts"]

    assert len(entries) == counts["imagines"], (
        f"imagine_table.json: {len(entries)} entries in 'imagines' but "
        f"_counts.imagines says {counts['imagines']}"
    )
    distinct_names = {e["name"] for e in entries}
    distinct_icons = {e["icon"] for e in entries}
    assert len(distinct_names) == counts["distinct_names"], (
        f"imagine_table.json: {len(distinct_names)} distinct names but "
        f"_counts.distinct_names says {counts['distinct_names']}"
    )
    assert len(distinct_icons) == counts["distinct_icons"], (
        f"imagine_table.json: {len(distinct_icons)} distinct icons but "
        f"_counts.distinct_icons says {counts['distinct_icons']}"
    )

    missing = sorted(
        icon for icon in distinct_icons if not (ASSETS / f"{icon}.png").is_file()
    )
    if missing:
        raise SystemExit(
            "refusing to emit: the following icon basenames are referenced by "
            f"imagine_table.json but have no PNG under {ASSETS}:\n  "
            + "\n  ".join(missing)
        )

    # Identity-is-the-icon invariants (design correction after review caught
    # the original name-dedup bug): these are what make "resolve every id to
    # its canonical (39xx) name" a safe, well-defined operation. Data-
    # dependent, so — like the asset-existence check above — they run here
    # rather than in `_self_test()`, which only exercises the pure helpers
    # against synthetic data.
    canonical_range = [e for e in entries if 3900 <= e["id"] < 4000]
    canonical_range_icons = {e["icon"] for e in canonical_range}
    canonical_range_names = {e["name"] for e in canonical_range}
    if len(canonical_range_icons) != 81 or len(canonical_range_names) != 81:
        raise SystemExit(
            "refusing to emit: expected exactly 81 distinct icons and 81 "
            "distinct names among ids 3900-3999 (the canonical range), got "
            f"{len(canonical_range_icons)} icons / {len(canonical_range_names)} names"
        )
    canonical_by_icon = canonical_name_by_icon(entries)  # raises if non-bijective
    if len(set(canonical_by_icon.values())) != len(canonical_by_icon):
        raise SystemExit(
            "refusing to emit: two different canonical icons share the same "
            "canonical name - the icon<->name bijection is broken"
        )
    canonical_name_of_id = resolve_canonical_names(entries, canonical_by_icon)  # raises on orphans
    assert set(canonical_name_of_id) == {e["id"] for e in entries}, (
        "canonical-name resolution must be total over every curated id"
    )

    out = io.StringIO()
    out.write(HEADER)
    emit_lookup(out, entries, canonical_name_of_id)
    emit_icon_bytes(out, sorted(distinct_icons))
    emit_all_entries(out, entries)
    OUT.write_text(out.getvalue())
    print(
        f"wrote {OUT}: {len(entries)} imagines, {len(distinct_names)} distinct raw names, "
        f"{len(distinct_icons)} distinct icons, {len(canonical_by_icon)} canonical names"
    )


if __name__ == "__main__":
    main()
