#!/usr/bin/env python3
"""Regenerate `crates/app/src/skill_icons.rs` from the committed skill icons.

`crates/app/assets/skills/` holds the vendored, downscaled, circle-masked skill
icons (issue #192) prepared by `scripts/prep-skill-icons.py` from the game
client via BPSR-ZDPS; see `THIRD_PARTY_NOTICES.md`. Do not edit by hand.

The directory listing, not the vendored id -> icon table
(`crates/meter/data/SkillOverridesIcons.json`), is the input on purpose. That
table names every icon BPSR-ZDPS references, including basenames whose art is
not present upstream and therefore not shipped here; compiling in only what is
actually committed keeps `include_bytes!` from naming a missing file, and the
runtime lookup already degrades a basename with no texture to a blank
placeholder.

Issue #348: a number of committed icons turned out to be byte-identical
placeholder art saved under two different basenames (all so far within this
one directory — see `DUPLICATE_ALIASES` below for basenames whose own PNG was
removed once that was confirmed). This script content-hashes every committed
PNG and, for any two that are byte-identical, emits only one `include_bytes!`
(for the alphabetically-first committed basename) and has every other basename in the
group's `SKILL_ICON_BYTES` entry reuse that same `static` instead of
compiling in its own copy of the same bytes.

Usage:

    python3 scripts/gen-skill-icons.py          # regenerate from the committed PNGs
    python3 scripts/gen-skill-icons.py --check  # offline: fail if skill_icons.rs is stale

Run `cargo fmt -p ShinraMeter-BPSR` after a regeneration.
`.github/workflows/name-tables.yml` runs `--check` so the generated file cannot
rot silently.
"""

import argparse
import hashlib
import io
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from _skill_aliases import DUPLICATE_ALIASES

ROOT = pathlib.Path(__file__).resolve().parent.parent
ASSETS = ROOT / "crates" / "app" / "assets" / "skills"
OUT = ROOT / "crates" / "app" / "src" / "skill_icons.rs"

# What a basename is allowed to be. These names end up inside a `concat!` path
# in an `include_bytes!`, so anything with a quote, a backslash or a path
# separator in it must be rejected here rather than emitted into Rust source.
# `scripts/gen-name-tables.py`'s `_ICON_BASENAME_RE` enforces the same shape on
# the table side.
BASENAME_RE = re.compile(r"^[A-Za-z0-9_.-]+$")

HEADER = '''//! The vendored skill-row icon basenames, compiled into the executable via
//! `include_bytes!` (issue #192).
//!
//! Generated by `scripts/gen-skill-icons.py` from the PNGs committed under
//! `crates/app/assets/skills/`, themselves prepared by
//! `scripts/prep-skill-icons.py` from the game client via BPSR-ZDPS; see
//! `THIRD_PARTY_NOTICES.md`. Do not edit by hand.
//!
//! This module is only the *bytes* half of skill icons. The skill id -> icon
//! basename half is `bpsr_meter::tables::skill_icon`, generated separately by
//! `scripts/gen-name-tables.py`. The two are deliberately not required to
//! agree: that table names every icon BPSR-ZDPS references, this module
//! carries only the subset whose art is actually committed here, and
//! `crate::icons::SkillIcons::get` returns `None` for the difference so the
//! row paints a blank placeholder instead of panicking.
//!
//! Issue #348: some basenames below share byte-identical PNGs. Rather than
//! compiling in the same bytes twice, only the alphabetically-first committed
//! basename in each such group gets its own `include_bytes!`; every other member's
//! `SKILL_ICON_BYTES` entry reuses that group leader's `static`. A basename
//! whose own PNG was deleted once this was discovered (so it no longer has a
//! file under `crates/app/assets/skills/` at all) is listed in
//! `scripts/_skill_aliases.py`'s `DUPLICATE_ALIASES` and still appears below,
//! still resolving to bytes.

/// Generates `SKILL_ICON_FILES` (every committed-or-aliased icon basename).
/// Production code only ever needs `SKILL_ICON_BYTES` below, so this is
/// `#[cfg(test)]`-gated the same way `imagine_icons!` in `crate::imagines`
/// gates `IMAGINE_ICON_FILES`.
macro_rules! skill_icon_names {
    ($($name:literal),+ $(,)?) => {
        #[cfg(test)]
        pub const SKILL_ICON_FILES: &[&str] = &[$($name),+];
    };
}
skill_icon_names! {
'''

NAMES_FOOTER = "}\n"

DUPLICATE_GROUP_COMMENT = (
    "\n"
    "// Content-duplicate groups (issue #348): every name below shares\n"
    "// byte-identical PNG content with at least one other committed or\n"
    "// aliased basename. Each group's alphabetically-first committed member\n"
    "// is the only one `include_bytes!`d; see `SKILL_ICON_BYTES` below for how the\n"
    "// rest reuse it.\n"
)

BYTES_HEADER = "pub const SKILL_ICON_BYTES: &[(&str, &[u8])] = &[\n"
BYTES_FOOTER = "];\n"

TESTS = '''
#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    #[test]
    fn duplicate_content_shares_one_embedded_copy() {
        // Issue #348: two basenames with byte-identical PNGs must reuse the
        // same embedded slice (same pointer) rather than each carrying its
        // own `include_bytes!` copy. A pointer mismatch here means the
        // generator failed to recognize a duplicate.
        let mut first_by_content: HashMap<&[u8], &str> = HashMap::new();
        for &(name, bytes) in SKILL_ICON_BYTES {
            match first_by_content.get(bytes) {
                Some(&first_name) => {
                    let first_bytes = SKILL_ICON_BYTES
                        .iter()
                        .find(|(n, _)| *n == first_name)
                        .unwrap()
                        .1;
                    assert_eq!(
                        bytes.as_ptr(),
                        first_bytes.as_ptr(),
                        "{name} and {first_name} have byte-identical PNGs but are embedded as separate copies"
                    );
                }
                None => {
                    first_by_content.insert(bytes, name);
                }
            }
        }
    }

    #[test]
    fn skill_icon_files_matches_skill_icon_bytes() {
        // Issue #348: `SKILL_ICON_FILES` and `SKILL_ICON_BYTES` are emitted
        // by two separate loops over the same `all_names` list, so nothing
        // structurally guarantees they stay in the same order or even name
        // the same set. Assert it here instead.
        let names: Vec<&str> = SKILL_ICON_BYTES.iter().map(|(n, _)| *n).collect();
        assert_eq!(names, SKILL_ICON_FILES);
        assert!(
            SKILL_ICON_FILES.windows(2).all(|w| w[0] < w[1]),
            "SKILL_ICON_FILES must be strictly ascending"
        );
    }
ALIAS_TEST_PLACEHOLDER}
'''


def _mangle(name: str) -> str:
    """A committed basename, upper-cased into a valid Rust `static` ident."""
    return re.sub(r"[^A-Za-z0-9]", "_", name).upper()


def group_leaders(
    committed_contents: dict[str, bytes], aliases: dict[str, str] | None = None
) -> dict[str, str]:
    """Map every committed name to its content group's leader (itself, if its
    content is unique among `committed_contents`), using the
    alphabetically-first committed name in a group as that group's leader.

    `aliases` (basename -> canonical basename) is folded in on top: each
    alias resolves through whatever group its canonical name landed in
    (normally just itself, but this chains correctly even if the canonical
    name is itself later found to duplicate a third file).
    """
    by_hash: dict[bytes, list[str]] = {}
    for name in sorted(committed_contents):
        digest = hashlib.sha256(committed_contents[name]).digest()
        by_hash.setdefault(digest, []).append(name)
    leaders: dict[str, str] = {}
    for members in by_hash.values():
        leader = min(members)
        for member in members:
            leaders[member] = leader
    for alias, canonical in (aliases or {}).items():
        leaders[alias] = leaders.get(canonical, canonical)
    return leaders


def validate_aliases(aliases: dict[str, str], committed: list[str]) -> None:
    """Raise `ValueError` if `aliases` (basename -> canonical basename) is
    inconsistent with what's actually committed under `ASSETS`: an alias
    whose own PNG is still committed, an alias pointing at a canonical name
    that isn't committed, or an alias unfit for an `include_bytes!` path.
    """
    committed_set = set(committed)
    for alias, canonical in aliases.items():
        if alias in committed_set:
            raise ValueError(
                f"{alias}.png is still committed under {ASSETS} but its alias entry "
                f"says its file was deleted as a duplicate of {canonical} — delete the "
                f"PNG or drop the alias entry"
            )
        if canonical not in committed_set:
            raise ValueError(
                f"an alias entry maps {alias} -> {canonical}, but {canonical}.png is "
                f"not committed under {ASSETS}"
            )
        if not BASENAME_RE.match(alias):
            raise ValueError(f"alias {alias!r} is unfit for an include_bytes! path")


def render(
    committed: list[str], committed_contents: dict[str, bytes], aliases: dict[str, str]
) -> str:
    validate_aliases(aliases, committed)
    leaders = group_leaders(committed_contents, aliases)

    all_names = sorted(set(committed) | set(aliases))

    # A name needs its own named `static` only if something else points at
    # it — i.e. it leads a group with more than one member.
    group_sizes: dict[str, int] = {}
    for name in all_names:
        group_sizes[leaders[name]] = group_sizes.get(leaders[name], 0) + 1
    leaders_with_followers = sorted(
        leader for leader, size in group_sizes.items() if size > 1
    )
    ident_for = {leader: f"ICON_{_mangle(leader)}" for leader in leaders_with_followers}
    if len(set(ident_for.values())) != len(ident_for):
        by_ident: dict[str, list[str]] = {}
        for leader, ident in ident_for.items():
            by_ident.setdefault(ident, []).append(leader)
        colliding = [leaders for leaders in by_ident.values() if len(leaders) > 1]
        raise ValueError(
            f"group leader basenames collide once mangled into a Rust ident: {colliding}"
        )

    out = io.StringIO()
    out.write(HEADER)
    for name in all_names:
        out.write(f'    "{name}",\n')
    out.write(NAMES_FOOTER)

    if leaders_with_followers:
        out.write(DUPLICATE_GROUP_COMMENT)
        for leader in leaders_with_followers:
            out.write(
                f'static {ident_for[leader]}: &[u8] = include_bytes!("../assets/skills/{leader}.png");\n'
            )

    out.write("\n")
    out.write(BYTES_HEADER)
    for name in all_names:
        leader = leaders[name]
        if leader == name and group_sizes[leader] == 1:
            # `rustfmt` always breaks a tuple containing a macro-call
            # argument onto multiple lines, regardless of width — matched
            # here so `--check` doesn't drift the moment `cargo fmt` runs.
            out.write(
                f'    (\n        "{name}",\n        include_bytes!("../assets/skills/{name}.png"),\n    ),\n'
            )
        else:
            out.write(f'    ("{name}", {ident_for[leader]}),\n')
    out.write(BYTES_FOOTER)
    out.write(TESTS.replace("ALIAS_TEST_PLACEHOLDER", _alias_test(aliases)))
    return out.getvalue()


def _alias_test(aliases: dict[str, str]) -> str:
    """The `DELETED_ALIASES` const and its one generic test, generated from
    `aliases` (issue #348, O5) — empty when there are no aliases, so a repo
    with no deleted-duplicate history never carries a vacuous test.
    """
    if not aliases:
        return ""
    entries = [f'("{alias}", "{canonical}")' for alias, canonical in sorted(aliases.items())]
    # Match what `cargo fmt` (max_width = 100, the rustfmt default) would do
    # with this const, since `--check` compares our raw output directly
    # against the committed file rather than running it through rustfmt.
    one_line = f'    const DELETED_ALIASES: &[(&str, &str)] = &[{", ".join(entries)}];'
    if len(one_line) <= 100:
        array_src = one_line
    else:
        rows = "\n".join(f"        {entry}," for entry in entries)
        array_src = f"    const DELETED_ALIASES: &[(&str, &str)] = &[\n{rows}\n    ];"
    return f'''
    // Basename pairs whose alias (first) had its own PNG deleted as a
    // byte-identical duplicate of its canonical name (second) — see
    // `DUPLICATE_ALIASES` in `scripts/gen-skill-icons.py` / `_skill_aliases.py`.
    #[cfg(test)]
{array_src}

    #[test]
    fn deleted_duplicate_alias_still_resolves() {{
        // Issue #348: an alias's own PNG was deleted once content hashing
        // confirmed it was byte-identical to its canonical name's, but
        // `crates/meter/data/SkillTableIcons.json` may still name the alias
        // directly (e.g. skill id 2900603 -> `weapon_sf-01_skill_03`), so it
        // must keep resolving to the canonical's shared bytes rather than
        // dropping out of `SKILL_ICON_BYTES`.
        for &(alias, canonical) in DELETED_ALIASES {{
            let canonical_bytes = SKILL_ICON_BYTES
                .iter()
                .find(|(n, _)| *n == canonical)
                .unwrap()
                .1;
            let alias_bytes = SKILL_ICON_BYTES
                .iter()
                .find(|(n, _)| *n == alias)
                .unwrap()
                .1;
            assert_eq!(canonical_bytes, alias_bytes);
            assert_eq!(canonical_bytes.as_ptr(), alias_bytes.as_ptr());
        }}
    }}
'''


def _self_test() -> None:
    """Fast synthetic checks run on every invocation. Same rationale as
    `scripts/gen-name-tables.py`'s `_self_test`: there is no Python test
    harness in this repo, so this hard-fails inline.
    """
    assert BASENAME_RE.match("weapon_mz-01_kx06")
    assert not BASENAME_RE.match("From Shield Combo talent")
    assert not BASENAME_RE.match("../evil")
    assert not BASENAME_RE.match('quote"')

    leaders = group_leaders({"b": b"x", "a": b"x", "c": b"y"})
    assert leaders == {"a": "a", "b": "a", "c": "c"}, leaders

    rendered = render(["a", "b"], {"a": b"x", "b": b"y"}, aliases={})
    assert '"a"' in rendered and '"b"' in rendered, rendered
    assert "static ICON_" not in rendered, "no duplicate content: no static should be emitted"

    dup_rendered = render(["a", "b"], {"a": b"x", "b": b"x"}, aliases={})
    assert "static ICON_A: &[u8]" in dup_rendered, dup_rendered
    assert '("b", ICON_A)' in dup_rendered, dup_rendered
    assert 'include_bytes!("../assets/skills/b.png")' not in dup_rendered, dup_rendered

    # An alias whose canonical is absent from the group (never a size > 1
    # group on its own) must still get a `static` and be reachable through it.
    alias_rendered = render(["a", "b"], {"a": b"x", "b": b"y"}, aliases={"c": "a"})
    assert "static ICON_A: &[u8]" in alias_rendered, alias_rendered
    assert '("a", ICON_A)' in alias_rendered, alias_rendered
    assert '("c", ICON_A)' in alias_rendered, alias_rendered

    try:
        render(["a", "b"], {"a": b"x", "b": b"y"}, aliases={"c": "zzz"})
        raise AssertionError("alias pointing at an uncommitted canonical should raise")
    except ValueError:
        pass

    try:
        render(
            ["a-b", "a_b"],
            {"a-b": b"x", "a_b": b"y"},
            aliases={"c": "a-b", "d": "a_b"},
        )
        raise AssertionError("group leaders that mangle to the same ident should raise")
    except ValueError:
        pass


def main() -> None:
    _self_test()

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; fail if the generated file is stale",
    )
    args = parser.parse_args()

    committed = sorted(p.stem for p in ASSETS.glob("*.png"))
    if not committed:
        sys.exit(f"no icons committed under {ASSETS}")
    bad = [n for n in committed if not BASENAME_RE.match(n)]
    if bad:
        sys.exit(f"{len(bad)} icon name(s) unfit for an include_bytes! path: {', '.join(bad)}")

    committed_contents = {n: (ASSETS / f"{n}.png").read_bytes() for n in committed}

    try:
        rendered = render(committed, committed_contents, aliases=DUPLICATE_ALIASES)
    except ValueError as exc:
        sys.exit(str(exc))
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else None
    if current == rendered:
        print(f"skill_icons.rs is up to date ({len(committed) + len(DUPLICATE_ALIASES)} icons)")
        return
    if args.check:
        sys.exit(
            f"skill_icons.rs is stale: regenerate with "
            f"`python3 scripts/gen-skill-icons.py` and run `cargo fmt`"
        )
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT} ({len(committed) + len(DUPLICATE_ALIASES)} icons)")


if __name__ == "__main__":
    main()
