#!/usr/bin/env python3
"""Regenerate `crates/meter/src/tables.rs` from the vendored name tables.

The community trackers publish their monster and scene name maps as JSON. We
keep verbatim copies under `crates/meter/data/` for provenance and compile them
into `match` arms so the lookup is free at runtime and the binary carries no
JSON parser for them.

To refresh, re-download the sources into `crates/meter/data/` and run this:

    curl -sLo crates/meter/data/MonsterName.json \\
      https://raw.githubusercontent.com/resonance-logs/resonance-logs/main/src-tauri/meter-data/MonsterName.json
    curl -sLo crates/meter/data/SceneName.json \\
      https://raw.githubusercontent.com/resonance-logs/resonance-logs/main/src-tauri/meter-data/SceneName.json
    curl -sLo crates/meter/data/MonsterNameCrowdsource.json \\
      https://raw.githubusercontent.com/winjwinj/bpsr-logs/main/src/lib/data/json/MonsterNameCrowdsource.json
    curl -sLo crates/meter/data/MonsterNameBoss.json \\
      https://raw.githubusercontent.com/winjwinj/bpsr-logs/main/src/lib/data/json/MonsterNameBoss.json
    python3 scripts/gen-name-tables.py && cargo fmt -p bpsr-meter
"""

import io
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "crates" / "meter" / "data"
OUT = ROOT / "crates" / "meter" / "src" / "tables.rs"

HEADER = """//! Static id -> display-name tables for monsters and scenes.
//!
//! Generated by `scripts/gen-name-tables.py` from the community-maintained
//! tables under `crates/meter/data/`, shipped by the `resonance-logs` and
//! `bpsr-logs` trackers (both GPL-3.0, the same licence as this project); see
//! `THIRD_PARTY_NOTICES.md`. Do not edit by hand.
//!
//! Coverage is partial - these tables name the monsters and instances the
//! community has catalogued, not every entity in the game. An unknown id yields
//! `None`, and callers fall back to showing the raw id.
"""

FOOTER = """
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names_a_known_raid_boss() {
        assert_eq!(monster_name(1013), Some("Rathalos"));
    }

    #[test]
    fn is_boss_monster_true_for_a_known_boss_id() {
        assert!(is_boss_monster(103));
    }

    #[test]
    fn is_boss_monster_false_for_a_known_non_boss_monster_id() {
        // "Golden Nappo" (10900) has a name in `monster_name` but is not in
        // `MonsterNameBoss.json` — a named-but-non-boss id must not read as
        // a boss just because the community table happens to know its name.
        assert!(!is_boss_monster(10_900));
    }

    #[test]
    fn is_boss_monster_boundary_ids() {
        assert!(is_boss_monster(103)); // lowest id in the set
        assert!(is_boss_monster(7_700_001)); // highest id in the set
        assert!(!is_boss_monster(102)); // just below the lowest
        assert!(!is_boss_monster(7_700_002)); // just above the highest
    }

    #[test]
    fn crowdsourced_entries_are_present_in_the_generated_table() {
        // NB: this only proves `MonsterNameCrowdsource.json` entries make it
        // into the table at all — every id that currently overlaps between
        // `MonsterName.json` and `MonsterNameCrowdsource.json` holds a
        // byte-identical value, so this table can't express (and this test
        // can't exercise) which side wins on a real disagreement. That
        // precedence is covered where it's actually decided:
        // `merge_monster_names`'s self-test in `scripts/gen-name-tables.py`.
        assert_eq!(monster_name(10086), Some("Goblin King"));
    }

    #[test]
    fn names_a_known_scene() {
        assert_eq!(scene_name(1001), Some("Tina's Mindrealm"));
    }

    #[test]
    fn unknown_ids_are_none() {
        assert_eq!(monster_name(0), None);
        assert_eq!(scene_name(0), None);
    }
}
"""


def esc(s: str) -> str:
    """Escape `s` for embedding in a Rust `&'static str` literal.

    Order matters: backslash is escaped first, so the escapes this function
    inserts below are never themselves re-escaped. `\\r`, `\\n`, and `\\t`
    get Rust's short forms; every other control character gets Rust's
    `\\u{...}` form, so a bare CR (or any other control byte) in a future
    refresh of the vendored community JSON can never produce a `tables.rs`
    that fails to compile with "bare CR not allowed in string" or similar.
    """
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    out = []
    for ch in s:
        if ch == "\r":
            out.append("\\r")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append(f"\\u{{{ord(ch):x}}}")
        else:
            out.append(ch)
    return "".join(out)


def merge_monster_names(bulk: dict[int, str], curated: dict[int, str]) -> dict[int, str]:
    """Merge the bulk community table with the hand-checked crowdsourced one.

    The crowdsourced list is hand-checked, so it must win where the two
    disagree: `curated` is applied on top of `bulk`, never the reverse.
    Pulled out as its own function so `_self_test` can exercise the
    precedence directly — today's two vendored JSON files agree on every id
    they share, so a generated `tables.rs` (and the Rust test that reads
    from it) can't tell a correct merge from a silently flipped one.
    """
    merged = dict(bulk)
    merged.update(curated)
    return merged


def _self_test() -> None:
    """Fast synthetic checks run on every generation. There is no Python
    test harness elsewhere in this repo (no pytest config, no CI job that
    runs Python — see `scripts/` and `.github/workflows/`), so this hard-fails
    inline instead of living in an untested, never-run test file.
    """
    merged = merge_monster_names({1: "Bulk Only", 2: "Bulk Version"}, {2: "Curated Version"})
    assert merged == {1: "Bulk Only", 2: "Curated Version"}, (
        "curated entries must win over the bulk table when ids overlap"
    )

    assert esc('a\\b"c') == 'a\\\\b\\"c'
    assert esc("line1\rline2") == "line1\\rline2"
    assert esc("line1\nline2") == "line1\\nline2"
    assert esc("a\tb") == "a\\tb"
    assert esc("\x01") == "\\u{1}"
    assert esc("\x7f") == "\\u{7f}"
    # Order: backslash-escaping must not re-escape a literal `\r` that was
    # already produced for a real carriage return.
    assert esc("\\\r") == "\\\\\\r"


def emit(out: io.StringIO, doc: str, fn: str, table: dict) -> None:
    out.write(f"\n{doc}\npub fn {fn}(id: u32) -> Option<&'static str> {{\n")
    out.write("    Some(match id {\n")
    for key in sorted(table):
        out.write('        %d => "%s",\n' % (key, esc(table[key])))
    out.write("        _ => return None,\n    })\n}\n")


BOSS_IDS_DOC = """/// Boss-monster template ids (issue #42): the top-bar encounter name should
/// only ever appear for a genuine boss fight. `Meter::recompute_boss`
/// (`crates/meter/src/encounter.rs`) picks whichever damaged enemy has the
/// largest known `max_hp` — a pure heuristic with no boss/trash
/// classification — so without this list a big trash mob would flash its
/// name in the header exactly like a real boss. This gates *display* only:
/// `EncounterInfo::boss_monster_id` stays populated for every pull regardless
/// of membership here; only `boss_name`/`is_boss` (set in `Meter::snapshot`)
/// are gated by it.
///
/// Generated from `crates/meter/data/MonsterNameBoss.json`, shipped
/// identically by the `bpsr-logs` and `resonance-logs` community trackers
/// (both GPL-3.0, the same licence as this project); see
/// `THIRD_PARTY_NOTICES.md`.
///
/// Sorted ascending; `is_boss_monster` binary-searches it."""

# rustfmt's own array-literal packing: greedily fill each line up to this
# width (indent included) before wrapping, matching the `#[rustfmt::skip]`
# formatting the array was originally written with so a diff against a
# hand-formatted file stays empty.
_BOSS_IDS_LINE_WIDTH = 96
_BOSS_IDS_INDENT = "    "


def emit_boss_ids(out: io.StringIO, ids: list[int]) -> None:
    out.write(f"\n{BOSS_IDS_DOC}\n#[rustfmt::skip]\nconst BOSS_MONSTER_IDS: &[u32] = &[\n")
    line = _BOSS_IDS_INDENT
    for n in ids:
        piece = f"{n}, "
        if line != _BOSS_IDS_INDENT and len(line) + len(piece) > _BOSS_IDS_LINE_WIDTH:
            out.write(line.rstrip() + "\n")
            line = _BOSS_IDS_INDENT
        line += piece
    if line != _BOSS_IDS_INDENT:
        out.write(line.rstrip() + "\n")
    out.write("];\n")
    out.write(
        "\n/// Whether `id` is a known boss-monster template id (issue #42) — i.e.\n"
        "/// whether the encounter name should ever be surfaced for it.\n"
        "pub fn is_boss_monster(id: u32) -> bool {\n"
        "    BOSS_MONSTER_IDS.binary_search(&id).is_ok()\n"
        "}\n"
    )


def main() -> None:
    _self_test()

    bulk = json.loads((DATA / "MonsterName.json").read_text())
    curated = json.loads((DATA / "MonsterNameCrowdsource.json").read_text())
    scenes = json.loads((DATA / "SceneName.json").read_text())
    bosses = json.loads((DATA / "MonsterNameBoss.json").read_text())

    monsters = merge_monster_names(
        {int(k): v for k, v in bulk.items()},
        {int(k): v for k, v in curated.items()},
    )
    boss_ids = sorted(int(k) for k in bosses)

    out = io.StringIO()
    out.write(HEADER)
    emit(
        out,
        "/// Display name for a monster template id, if the community table names it.",
        "monster_name",
        monsters,
    )
    emit(
        out,
        "/// Display name for a scene (map/instance) id, if the community table names it.",
        "scene_name",
        {int(k): v for k, v in scenes.items()},
    )
    emit_boss_ids(out, boss_ids)
    out.write(FOOTER)
    OUT.write_text(out.getvalue())
    print(
        f"wrote {OUT}: {len(monsters)} monsters, {len(scenes)} scenes, "
        f"{len(boss_ids)} boss ids"
    )


if __name__ == "__main__":
    main()
